/*
 * Copyright (C) 2019 Alexander Borisov
 *
 * Author: Alexander Borisov <borisov@lexbor.com>
 */

/*
 * Caution!
 * This file generated by the script "utils/lexbor/encoding/multi-byte.py"!
 * Do not change this file!
 */

#include "lexbor/encoding/base.h"

#include "lexbor/core/shs.h"


LXB_API const lxb_encoding_multi_index_t lxb_encoding_multi_index_iso_2022_jp_katakana[63] = 
{
    {(lxb_char_t *) "\xe3\x80\x82", 3, 0x3002}, /* (IDEOGRAPHIC FULL STOP) */
    {(lxb_char_t *) "\xe3\x80\x8c", 3, 0x300C}, /* (LEFT CORNER BRACKET) */
    {(lxb_char_t *) "\xe3\x80\x8d", 3, 0x300D}, /* (RIGHT CORNER BRACKET) */
    {(lxb_char_t *) "\xe3\x80\x81", 3, 0x3001}, /* (IDEOGRAPHIC COMMA) */
    {(lxb_char_t *) "\xe3\x83\xbb", 3, 0x30FB}, /* (KATAKANA MIDDLE DOT) */
    {(lxb_char_t *) "\xe3\x83\xb2", 3, 0x30F2}, /* (KATAKANA LETTER WO) */
    {(lxb_char_t *) "\xe3\x82\xa1", 3, 0x30A1}, /* (KATAKANA LETTER SMALL A) */
    {(lxb_char_t *) "\xe3\x82\xa3", 3, 0x30A3}, /* (KATAKANA LETTER SMALL I) */
    {(lxb_char_t *) "\xe3\x82\xa5", 3, 0x30A5}, /* (KATAKANA LETTER SMALL U) */
    {(lxb_char_t *) "\xe3\x82\xa7", 3, 0x30A7}, /* (KATAKANA LETTER SMALL E) */
    {(lxb_char_t *) "\xe3\x82\xa9", 3, 0x30A9}, /* (KATAKANA LETTER SMALL O) */
    {(lxb_char_t *) "\xe3\x83\xa3", 3, 0x30E3}, /* (KATAKANA LETTER SMALL YA) */
    {(lxb_char_t *) "\xe3\x83\xa5", 3, 0x30E5}, /* (KATAKANA LETTER SMALL YU) */
    {(lxb_char_t *) "\xe3\x83\xa7", 3, 0x30E7}, /* (KATAKANA LETTER SMALL YO) */
    {(lxb_char_t *) "\xe3\x83\x83", 3, 0x30C3}, /* (KATAKANA LETTER SMALL TU) */
    {(lxb_char_t *) "\xe3\x83\xbc", 3, 0x30FC}, /* (KATAKANA-HIRAGANA PROLONGED SOUND MARK) */
    {(lxb_char_t *) "\xe3\x82\xa2", 3, 0x30A2}, /* (KATAKANA LETTER A) */
    {(lxb_char_t *) "\xe3\x82\xa4", 3, 0x30A4}, /* (KATAKANA LETTER I) */
    {(lxb_char_t *) "\xe3\x82\xa6", 3, 0x30A6}, /* (KATAKANA LETTER U) */
    {(lxb_char_t *) "\xe3\x82\xa8", 3, 0x30A8}, /* (KATAKANA LETTER E) */
    {(lxb_char_t *) "\xe3\x82\xaa", 3, 0x30AA}, /* (KATAKANA LETTER O) */
    {(lxb_char_t *) "\xe3\x82\xab", 3, 0x30AB}, /* (KATAKANA LETTER KA) */
    {(lxb_char_t *) "\xe3\x82\xad", 3, 0x30AD}, /* (KATAKANA LETTER KI) */
    {(lxb_char_t *) "\xe3\x82\xaf", 3, 0x30AF}, /* (KATAKANA LETTER KU) */
    {(lxb_char_t *) "\xe3\x82\xb1", 3, 0x30B1}, /* (KATAKANA LETTER KE) */
    {(lxb_char_t *) "\xe3\x82\xb3", 3, 0x30B3}, /* (KATAKANA LETTER KO) */
    {(lxb_char_t *) "\xe3\x82\xb5", 3, 0x30B5}, /* (KATAKANA LETTER SA) */
    {(lxb_char_t *) "\xe3\x82\xb7", 3, 0x30B7}, /* (KATAKANA LETTER SI) */
    {(lxb_char_t *) "\xe3\x82\xb9", 3, 0x30B9}, /* (KATAKANA LETTER SU) */
    {(lxb_char_t *) "\xe3\x82\xbb", 3, 0x30BB}, /* (KATAKANA LETTER SE) */
    {(lxb_char_t *) "\xe3\x82\xbd", 3, 0x30BD}, /* (KATAKANA LETTER SO) */
    {(lxb_char_t *) "\xe3\x82\xbf", 3, 0x30BF}, /* (KATAKANA LETTER TA) */
    {(lxb_char_t *) "\xe3\x83\x81", 3, 0x30C1}, /* (KATAKANA LETTER TI) */
    {(lxb_char_t *) "\xe3\x83\x84", 3, 0x30C4}, /* (KATAKANA LETTER TU) */
    {(lxb_char_t *) "\xe3\x83\x86", 3, 0x30C6}, /* (KATAKANA LETTER TE) */
    {(lxb_char_t *) "\xe3\x83\x88", 3, 0x30C8}, /* (KATAKANA LETTER TO) */
    {(lxb_char_t *) "\xe3\x83\x8a", 3, 0x30CA}, /* (KATAKANA LETTER NA) */
    {(lxb_char_t *) "\xe3\x83\x8b", 3, 0x30CB}, /* (KATAKANA LETTER NI) */
    {(lxb_char_t *) "\xe3\x83\x8c", 3, 0x30CC}, /* (KATAKANA LETTER NU) */
    {(lxb_char_t *) "\xe3\x83\x8d", 3, 0x30CD}, /* (KATAKANA LETTER NE) */
    {(lxb_char_t *) "\xe3\x83\x8e", 3, 0x30CE}, /* (KATAKANA LETTER NO) */
    {(lxb_char_t *) "\xe3\x83\x8f", 3, 0x30CF}, /* (KATAKANA LETTER HA) */
    {(lxb_char_t *) "\xe3\x83\x92", 3, 0x30D2}, /* (KATAKANA LETTER HI) */
    {(lxb_char_t *) "\xe3\x83\x95", 3, 0x30D5}, /* (KATAKANA LETTER HU) */
    {(lxb_char_t *) "\xe3\x83\x98", 3, 0x30D8}, /* (KATAKANA LETTER HE) */
    {(lxb_char_t *) "\xe3\x83\x9b", 3, 0x30DB}, /* (KATAKANA LETTER HO) */
    {(lxb_char_t *) "\xe3\x83\x9e", 3, 0x30DE}, /* (KATAKANA LETTER MA) */
    {(lxb_char_t *) "\xe3\x83\x9f", 3, 0x30DF}, /* (KATAKANA LETTER MI) */
    {(lxb_char_t *) "\xe3\x83\xa0", 3, 0x30E0}, /* (KATAKANA LETTER MU) */
    {(lxb_char_t *) "\xe3\x83\xa1", 3, 0x30E1}, /* (KATAKANA LETTER ME) */
    {(lxb_char_t *) "\xe3\x83\xa2", 3, 0x30E2}, /* (KATAKANA LETTER MO) */
    {(lxb_char_t *) "\xe3\x83\xa4", 3, 0x30E4}, /* (KATAKANA LETTER YA) */
    {(lxb_char_t *) "\xe3\x83\xa6", 3, 0x30E6}, /* (KATAKANA LETTER YU) */
    {(lxb_char_t *) "\xe3\x83\xa8", 3, 0x30E8}, /* (KATAKANA LETTER YO) */
    {(lxb_char_t *) "\xe3\x83\xa9", 3, 0x30E9}, /* (KATAKANA LETTER RA) */
    {(lxb_char_t *) "\xe3\x83\xaa", 3, 0x30EA}, /* (KATAKANA LETTER RI) */
    {(lxb_char_t *) "\xe3\x83\xab", 3, 0x30EB}, /* (KATAKANA LETTER RU) */
    {(lxb_char_t *) "\xe3\x83\xac", 3, 0x30EC}, /* (KATAKANA LETTER RE) */
    {(lxb_char_t *) "\xe3\x83\xad", 3, 0x30ED}, /* (KATAKANA LETTER RO) */
    {(lxb_char_t *) "\xe3\x83\xaf", 3, 0x30EF}, /* (KATAKANA LETTER WA) */
    {(lxb_char_t *) "\xe3\x83\xb3", 3, 0x30F3}, /* (KATAKANA LETTER N) */
    {(lxb_char_t *) "\xe3\x82\x9b", 3, 0x309B}, /* (KATAKANA-HIRAGANA VOICED SOUND MARK) */
    {(lxb_char_t *) "\xe3\x82\x9c", 3, 0x309C}, /* (KATAKANA-HIRAGANA SEMI-VOICED SOUND MARK) */
};

/* Table size: 52; Max deep: 2 */
LXB_API const lexbor_shs_hash_t lxb_encoding_multi_hash_iso_2022_jp_katakana[72] = 
{
    {0, NULL, 0},{0, NULL, 0},
    {12481, (void *) 32, 0},
    {0, NULL, 0},
    {12483, (void *) 14, 0},
    {12484, (void *) 33, 0},
    {0, NULL, 0},
    {12486, (void *) 34, 0},
    {12539, (void *) 4, 0},
    {12540, (void *) 15, 58},
    {0, NULL, 0},
    {12490, (void *) 36, 0},
    {12491, (void *) 37, 0},
    {12492, (void *) 38, 0},
    {12493, (void *) 39, 0},
    {12494, (void *) 40, 0},
    {12495, (void *) 41, 71},
    {12444, (void *) 62, 0},
    {12289, (void *) 3, 0},
    {12290, (void *) 0, 59},
    {0, NULL, 0},
    {0, NULL, 0},
    {12449, (void *) 6, 60},
    {12450, (void *) 16, 0},
    {12451, (void *) 7, 0},
    {12452, (void *) 17, 61},
    {12453, (void *) 8, 0},
    {12454, (void *) 18, 0},
    {12455, (void *) 9, 62},
    {12300, (void *) 1, 54},
    {12301, (void *) 2, 53},
    {12458, (void *) 20, 63},
    {12459, (void *) 21, 64},
    {12512, (void *) 48, 0},
    {12461, (void *) 22, 65},
    {12514, (void *) 50, 0},
    {12515, (void *) 11, 55},
    {12516, (void *) 51, 0},
    {12517, (void *) 12, 56},
    {12518, (void *) 52, 0},
    {12519, (void *) 13, 57},
    {12520, (void *) 53, 0},
    {12469, (void *) 26, 66},
    {12522, (void *) 55, 0},
    {12471, (void *) 27, 67},
    {12524, (void *) 57, 0},
    {12473, (void *) 28, 68},
    {0, NULL, 0},
    {12475, (void *) 29, 69},
    {0, NULL, 0},
    {12477, (void *) 30, 0},
    {12530, (void *) 5, 0},
    {12479, (void *) 31, 70},
    {12457, (void *) 10, 0},
    {12456, (void *) 19, 0},
    {12463, (void *) 23, 0},
    {12465, (void *) 24, 0},
    {12467, (void *) 25, 0},
    {12488, (void *) 35, 0},
    {12498, (void *) 42, 0},
    {12501, (void *) 43, 0},
    {12504, (void *) 44, 0},
    {12507, (void *) 45, 0},
    {12510, (void *) 46, 0},
    {12511, (void *) 47, 0},
    {12513, (void *) 49, 0},
    {12521, (void *) 54, 0},
    {12523, (void *) 56, 0},
    {12525, (void *) 58, 0},
    {12527, (void *) 59, 0},
    {12531, (void *) 60, 0},
    {12443, (void *) 61, 0}
};
