if(NOT DEFINED LEXBOR_OPTIMIZATION_LEVEL)
	set(LEXBOR_OPTIMIZATION_LEVEL "-O2")
endif()

if(NOT DEFINED LEXBOR_C_FLAGS)
	set(LEXBOR_C_FLAGS "-Wall -pedantic -pipe -std=c99 -fPIC -Wunused-function")
endif()

set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} ${LEXBOR_OPTIMIZATION_LEVEL} ${LEXBOR_C_FLAGS}")

if(CMAKE_SYSTEM_NAME STREQUAL "Linux")
	add_definitions(-D_POSIX_C_SOURCE=199309L)
endif()
