/*
 * Copyright (C) 2018 Alexander Borisov
 *
 * Author: Alexander Borisov <lex.borisov@gmail.com>
 */

/*
 * Caution!!! Important!!!
 * This file generated by the script "utils/lexbor/html/tags.py"!
 * Do not change this file!
 */


#ifndef LXB_HTML_NS_CONST_H
#define LXB_HTML_NS_CONST_H

#define LXB_HTML_NS_CONST_VERSION "%%HASH%%"
#define LXB_HTML_NS_CONST_VERSION_%%HASH%%

typedef unsigned int lxb_html_ns_id_t;

%%BODY%%


#endif /* LXB_HTML_NS_CONST_H */
