/*
 * Copyright (C) 2018 Alexander Borisov
 *
 * Author: Alexander Borisov <borisov@lexbor.com>
 */

/*
 * Caution!!! Important!!!
 * This file generated by the script
 * "utils/lexbor/html/tokenizer_entities_bst.py"!
 * Do not change this file!
 */


#ifndef LXB_HTML_TOKENIZER_RES_H
#define LXB_HTML_TOKENIZER_RES_H

#endif /* LXB_HTML_TOKENIZER_RES */


%%BODY%%
