/*
 * Copyright (C) 2019 Alexander Borisov
 *
 * Author: Alexander Borisov <lex.borisov@gmail.com>
 */

/*
 * Caution!
 * This file generated by the script "utils/lexbor/encoding/res.py"!
 * Do not change this file!
 */


#ifndef LEXBOR_ENCODING_CONST_H
#define LEXBOR_ENCODING_CONST_H

%%CONST%%

#endif /* LEXBOR_ENCODING_CONST_H */
