/*
 * Copyright (C) %%YEAR%% Alexander Borisov
 *
 * Author: Alexander Borisov <borisov@lexbor.com>
 */

/*
 * Caution!
 * This file generated by the script "utils/lexbor/encoding/multi-byte.py"!
 * Do not change this file!
 */


#ifndef LEXBOR_ENCODING_MULTI_H
#define LEXBOR_ENCODING_MULTI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lexbor/encoding/base.h"

#include "lexbor/core/shs.h"


%%SIZES%%

#ifndef LEXBOR_DISABLE_INTERNAL_EXTERN
%%EXTERNS%%
#endif /* !LEXBOR_DISABLE_INTERNAL_EXTERN */


#ifdef __cplusplus
} /* extern "C" */
#endif

#endif /* LEXBOR_ENCODING_MULTI_H */
