/*
 * Copyright (C) 2019 Alexander Borisov
 *
 * Author: Alexander Borisov <borisov@lexbor.com>
 */

/*
 * Caution!
 * This file generated by the script "utils/lexbor/encoding/range-byte.py"!
 * Do not change this file!
 */

#include "lexbor/encoding/base.h"


%%INDEX%%

