/*
 * Copyright (C) 2018 Alexander Borisov
 *
 * Author: Alexander Borisov <borisov@lexbor.com>
 */

/*
 * Caution!
 * This file generated by the script "utils/lexbor/tag_ns/tags.py"!
 * Do not change this file!
 */


#ifndef LXB_NS_RES_H
#define LXB_NS_RES_H

#endif /* LXB_NS_RES_H */


#ifdef LXB_NS_CONST_VERSION
#ifndef LXB_NS_CONST_VERSION_253D4AFDA959234B48A478B956C3C777
#error Mismatched namespaces version! See "lexbor/ns/const.h".
#endif /* LXB_NS_CONST_VERSION_253D4AFDA959234B48A478B956C3C777 */
#else
#error You need to include "lexbor/ns/const.h".
#endif /* LXB_NS_CONST_VERSION */

#ifdef LXB_NS_RES_DATA
#ifndef LXB_NS_RES_DATA_ENABLED
#define LXB_NS_RES_DATA_ENABLED
static  lxb_ns_data_t lxb_ns_res_data[LXB_NS__LAST_ENTRY] = 
{
    {"#undef", "#undef", 6, "", 0, LXB_NS__UNDEF},
    {"#any", "#any", 4, "", 0, LXB_NS__ANY},
    {"HTML", "html", 4, "http://www.w3.org/1999/xhtml", 28, LXB_NS_HTML},
    {"Math", "math", 4, "http://www.w3.org/1998/Math/MathML", 34, LXB_NS_MATH},
    {"SVG", "svg", 3, "http://www.w3.org/2000/svg", 26, LXB_NS_SVG},
    {"XLink", "xlink", 5, "http://www.w3.org/1999/xlink", 28, LXB_NS_XLINK},
    {"XML", "xml", 3, "http://www.w3.org/XML/1998/namespace", 36, LXB_NS_XML},
    {"XMLNS", "xmlns", 5, "http://www.w3.org/2000/xmlns/", 29, LXB_NS_XMLNS}
};
#endif /* LXB_NS_RES_DATA_ENABLED */
#endif /* LXB_NS_RES_DATA */

#ifdef LXB_NS_RES_SHS_LINK_DATA
#ifndef LXB_NS_RES_SHS_LINK_DATA_ENABLED
#define LXB_NS_RES_SHS_LINK_DATA_ENABLED
static const lexbor_shs_entry_t lxb_ns_res_shs_link_data[] = 
{
    {NULL, NULL, 22, 0}, {"http://www.w3.org/1999/xhtml", &lxb_ns_res_data[2], 28, 0}, 
    {NULL, NULL, 0, 0}, {NULL, NULL, 0, 0}, 
    {NULL, NULL, 0, 0}, {NULL, NULL, 0, 0}, 
    {"http://www.w3.org/2000/xmlns/", &lxb_ns_res_data[7], 29, 0}, {"http://www.w3.org/1998/Math/MathML", &lxb_ns_res_data[3], 34, 0}, 
    {NULL, NULL, 0, 0}, {"http://www.w3.org/1999/xlink", &lxb_ns_res_data[5], 28, 0}, 
    {NULL, NULL, 0, 0}, {NULL, NULL, 0, 0}, 
    {NULL, NULL, 0, 0}, {NULL, NULL, 0, 0}, 
    {NULL, NULL, 0, 0}, {NULL, NULL, 0, 0}, 
    {"#any", &lxb_ns_res_data[1], 4, 0}, {"http://www.w3.org/2000/svg", &lxb_ns_res_data[4], 26, 0}, 
    {NULL, NULL, 0, 0}, {"#undef", &lxb_ns_res_data[0], 6, 0}, 
    {NULL, NULL, 0, 0}, {"http://www.w3.org/XML/1998/namespace", &lxb_ns_res_data[6], 36, 0}, 
    {NULL, NULL, 0, 0}
};
#endif /* LXB_NS_RES_SHS_LINK_DATA_ENABLED */
#endif /* LXB_NS_RES_SHS_LINK_DATA */
