/*
 * Copyright (C) 2018-%%YEAR%% Alexander Borisov
 *
 * Author: Alexander Borisov <borisov@lexbor.com>
 */

/*
 * Caution!
 * This file generated by the script "utils/lexbor/tag_ns/tags.py"!
 * Do not change this file!
 */


#ifndef %%HEADER_GUARD%%
#define %%HEADER_GUARD%%

%%CHECK_TAG_VERSION%%

%%ATTRIBUTE_STEPS%%

#endif /* %%HEADER_GUARD%% */
