/*
 * Copyright (C) 2018 Alexander Borisov
 *
 * Author: Alexander Borisov <borisov@lexbor.com>
 */

/*
 * Caution!
 * This file generated by the script "utils/lexbor/tag_ns/tags.py"!
 * Do not change this file!
 */


#ifndef LXB_HTML_INTERFACE_RES_H
#define LXB_HTML_INTERFACE_RES_H

#endif /* LXB_HTML_INTERFACE_RES_H */

%%CHECK_TAG_VERSION%%

%%CHECK_NS_VERSION%%

%%INCLUDES%%

%%CONSTRUCTOR%%

%%DESTRUCTOR%%
