/*
 * Copyright (C) 2018-%%YEAR%% Alexander Borisov
 *
 * Author: Alexander Borisov <borisov@lexbor.com>
 */

/*
 * Caution!
 * This file generated by the script "utils/lexbor/tag_ns/tags.py"!
 * Do not change this file!
 */


#ifndef LXB_HTML_OPEN_ELEMENTS_RES_H
#define LXB_HTML_OPEN_ELEMENTS_RES_H

%%CHECK_TAG_VERSION%%

%%OPEN_ELEMENTS_POP%%

#endif /* LXB_HTML_OPEN_ELEMENTS_RES_H */
