/*
 * Copyright (C) 2018-2019 Alexander Borisov
 *
 * Author: Alexander Borisov <borisov@lexbor.com>
 */

/*
 * Caution!
 * This file generated by the script "utils/lexbor/tag_ns/tags.py"!
 * Do not change this file!
 */


#ifndef LXB_NS_RES_H
#define LXB_NS_RES_H

#endif /* LXB_NS_RES_H */


%%CHECK_NS_VERSION%%


%%NS_DATA%%

%%NS_PREFIX_DATA%%

%%SHS_DATA%%

%%SHS_DATA_LINK%%
