/*
 * Copyright (C) 2018 Alexander Borisov
 *
 * Author: Alexander Borisov <borisov@lexbor.com>
 */

/*
 * Caution!
 * This file generated by the script "utils/lexbor/tag_ns/tags.py"!
 * Do not change this file!
 */


#ifndef LXB_TAG_CONST_H
#define LXB_TAG_CONST_H

#define LXB_TAG_CONST_VERSION "%%HASH%%"
#define LXB_TAG_CONST_VERSION_%%HASH%%


typedef uintptr_t lxb_tag_id_t;

%%BODY%%


#endif /* LXB_TAG_CONST_H */
