/*
 * Copyright (C) 2018 Alexander Borisov
 *
 * Author: Alexander Borisov <borisov@lexbor.com>
 */

/*
 * Caution!
 * This file generated by the script "utils/lexbor/tag_ns/tags.py"!
 * Do not change this file!
 */


#ifndef LXB_TAG_RES_H
#define LXB_TAG_RES_H

#endif /* LXB_TAG_RES_H */

%%CHECK_TAG_VERSION%%

%%TAG_DATA%%

%%TAG_DATA_UPPER%%

%%SHS_DATA%%

