/*
 * Copyright (C) 2019 Alexander Borisov
 *
 * Author: Alexander Borisov <borisov@lexbor.com>
 */

/*
 * Caution!
 * This file generated by the script "utils/lexbor/dom/attr.py"!
 * Do not change this file!
 */


#ifndef LXB_DOM_ATTR_RES_H
#define LXB_DOM_ATTR_RES_H

#include "lexbor/core/shs.h"

#include "lexbor/dom/interfaces/attr_const.h"


static const lxb_dom_attr_data_t lxb_dom_attr_res_data_default[LXB_DOM_ATTR__LAST_ENTRY] = 
{
    {{.u.short_str = "#undef", .length = 6, .next = NULL},
     LXB_DOM_ATTR__UNDEF, 1, true},
    {{.u.short_str = "alt", .length = 3, .next = NULL},
     LXB_DOM_ATTR_ALT, 1, true},
    {{.u.short_str = "charser", .length = 7, .next = NULL},
     LXB_DOM_ATTR_CHARSER, 1, true},
    {{.u.short_str = "checked", .length = 7, .next = NULL},
     LXB_DOM_ATTR_CHECKED, 1, true},
    {{.u.short_str = "class", .length = 5, .next = NULL},
     LXB_DOM_ATTR_CLASS, 1, true},
    {{.u.short_str = "content", .length = 7, .next = NULL},
     LXB_DOM_ATTR_CONTENT, 1, true},
    {{.u.short_str = "dir", .length = 3, .next = NULL},
     LXB_DOM_ATTR_DIR, 1, true},
    {{.u.short_str = "disabled", .length = 8, .next = NULL},
     LXB_DOM_ATTR_DISABLED, 1, true},
    {{.u.short_str = "for", .length = 3, .next = NULL},
     LXB_DOM_ATTR_FOR, 1, true},
    {{.u.short_str = "height", .length = 6, .next = NULL},
     LXB_DOM_ATTR_HEIGHT, 1, true},
    {{.u.short_str = "href", .length = 4, .next = NULL},
     LXB_DOM_ATTR_HREF, 1, true},
    {{.u.short_str = "http-equiv", .length = 10, .next = NULL},
     LXB_DOM_ATTR_HTTP_EQUIV, 1, true},
    {{.u.short_str = "id", .length = 2, .next = NULL},
     LXB_DOM_ATTR_ID, 1, true},
    {{.u.short_str = "is", .length = 2, .next = NULL},
     LXB_DOM_ATTR_IS, 1, true},
    {{.u.short_str = "maxlength", .length = 9, .next = NULL},
     LXB_DOM_ATTR_MAXLENGTH, 1, true},
    {{.u.short_str = "pool", .length = 4, .next = NULL},
     LXB_DOM_ATTR_POOL, 1, true},
    {{.u.short_str = "scheme", .length = 6, .next = NULL},
     LXB_DOM_ATTR_SCHEME, 1, true},
    {{.u.short_str = "slot", .length = 4, .next = NULL},
     LXB_DOM_ATTR_SLOT, 1, true},
    {{.u.short_str = "src", .length = 3, .next = NULL},
     LXB_DOM_ATTR_SRC, 1, true},
    {{.u.short_str = "style", .length = 5, .next = NULL},
     LXB_DOM_ATTR_STYLE, 1, true},
    {{.u.short_str = "title", .length = 5, .next = NULL},
     LXB_DOM_ATTR_TITLE, 1, true},
    {{.u.short_str = "width", .length = 5, .next = NULL},
     LXB_DOM_ATTR_WIDTH, 1, true}
};

static const lexbor_shs_entry_t lxb_dom_attr_res_shs_data[] = 
{
    {NULL, NULL, 89, 0}, 
    {"#undef", (void *) &lxb_dom_attr_res_data_default[LXB_DOM_ATTR__UNDEF], 6, 0}, 
    {NULL, NULL, 0, 0}, 
    {"dir", (void *) &lxb_dom_attr_res_data_default[LXB_DOM_ATTR_DIR], 3, 0}, 
    {NULL, NULL, 0, 0}, 
    {"disabled", (void *) &lxb_dom_attr_res_data_default[LXB_DOM_ATTR_DISABLED], 8, 0}, 
    {NULL, NULL, 0, 0}, 
    {NULL, NULL, 0, 0}, 
    {NULL, NULL, 0, 0}, 
    {NULL, NULL, 0, 0}, 
    {NULL, NULL, 0, 0}, 
    {NULL, NULL, 0, 0}, 
    {"slot", (void *) &lxb_dom_attr_res_data_default[LXB_DOM_ATTR_SLOT], 4, 0}, 
    {NULL, NULL, 0, 0}, 
    {NULL, NULL, 0, 0}, 
    {NULL, NULL, 0, 0}, 
    {"charser", (void *) &lxb_dom_attr_res_data_default[LXB_DOM_ATTR_CHARSER], 7, 0}, 
    {NULL, NULL, 0, 0}, 
    {NULL, NULL, 0, 0}, 
    {"style", (void *) &lxb_dom_attr_res_data_default[LXB_DOM_ATTR_STYLE], 5, 0}, 
    {"scheme", (void *) &lxb_dom_attr_res_data_default[LXB_DOM_ATTR_SCHEME], 6, 0}, 
    {NULL, NULL, 0, 0}, 
    {NULL, NULL, 0, 0}, 
    {NULL, NULL, 0, 0}, 
    {NULL, NULL, 0, 0}, 
    {"class", (void *) &lxb_dom_attr_res_data_default[LXB_DOM_ATTR_CLASS], 5, 0}, 
    {NULL, NULL, 0, 0}, 
    {NULL, NULL, 0, 0}, 
    {NULL, NULL, 0, 0}, 
    {NULL, NULL, 0, 0}, 
    {"height", (void *) &lxb_dom_attr_res_data_default[LXB_DOM_ATTR_HEIGHT], 6, 0}, 
    {NULL, NULL, 0, 0}, 
    {"title", (void *) &lxb_dom_attr_res_data_default[LXB_DOM_ATTR_TITLE], 5, 0}, 
    {NULL, NULL, 0, 0}, 
    {NULL, NULL, 0, 0}, 
    {NULL, NULL, 0, 0}, 
    {NULL, NULL, 0, 0}, 
    {NULL, NULL, 0, 0}, 
    {"content", (void *) &lxb_dom_attr_res_data_default[LXB_DOM_ATTR_CONTENT], 7, 0}, 
    {"http-equiv", (void *) &lxb_dom_attr_res_data_default[LXB_DOM_ATTR_HTTP_EQUIV], 10, 0}, 
    {"checked", (void *) &lxb_dom_attr_res_data_default[LXB_DOM_ATTR_CHECKED], 7, 0}, 
    {"alt", (void *) &lxb_dom_attr_res_data_default[LXB_DOM_ATTR_ALT], 3, 0}, 
    {NULL, NULL, 0, 0}, 
    {NULL, NULL, 0, 0}, 
    {NULL, NULL, 0, 0}, 
    {NULL, NULL, 0, 0}, 
    {"for", (void *) &lxb_dom_attr_res_data_default[LXB_DOM_ATTR_FOR], 3, 0}, 
    {"maxlength", (void *) &lxb_dom_attr_res_data_default[LXB_DOM_ATTR_MAXLENGTH], 9, 0}, 
    {NULL, NULL, 0, 0}, 
    {NULL, NULL, 0, 0}, 
    {NULL, NULL, 0, 0}, 
    {NULL, NULL, 0, 0}, 
    {NULL, NULL, 0, 0}, 
    {NULL, NULL, 0, 0}, 
    {NULL, NULL, 0, 0}, 
    {NULL, NULL, 0, 0}, 
    {NULL, NULL, 0, 0}, 
    {NULL, NULL, 0, 0}, 
    {NULL, NULL, 0, 0}, 
    {NULL, NULL, 0, 0}, 
    {"id", (void *) &lxb_dom_attr_res_data_default[LXB_DOM_ATTR_ID], 2, 0}, 
    {NULL, NULL, 0, 0}, 
    {NULL, NULL, 0, 0}, 
    {NULL, NULL, 0, 0}, 
    {NULL, NULL, 0, 0}, 
    {NULL, NULL, 0, 0}, 
    {NULL, NULL, 0, 0}, 
    {"width", (void *) &lxb_dom_attr_res_data_default[LXB_DOM_ATTR_WIDTH], 5, 0}, 
    {NULL, NULL, 0, 0}, 
    {NULL, NULL, 0, 0}, 
    {NULL, NULL, 0, 0}, 
    {NULL, NULL, 0, 0}, 
    {NULL, NULL, 0, 0}, 
    {"is", (void *) &lxb_dom_attr_res_data_default[LXB_DOM_ATTR_IS], 2, 0}, 
    {NULL, NULL, 0, 0}, 
    {NULL, NULL, 0, 0}, 
    {NULL, NULL, 0, 0}, 
    {NULL, NULL, 0, 0}, 
    {NULL, NULL, 0, 0}, 
    {NULL, NULL, 0, 0}, 
    {NULL, NULL, 0, 0}, 
    {NULL, NULL, 0, 0}, 
    {"href", (void *) &lxb_dom_attr_res_data_default[LXB_DOM_ATTR_HREF], 4, 0}, 
    {NULL, NULL, 0, 0}, 
    {NULL, NULL, 0, 0}, 
    {NULL, NULL, 0, 0}, 
    {NULL, NULL, 0, 0}, 
    {NULL, NULL, 0, 0}, 
    {"pool", (void *) &lxb_dom_attr_res_data_default[LXB_DOM_ATTR_POOL], 4, 0}, 
    {"src", (void *) &lxb_dom_attr_res_data_default[LXB_DOM_ATTR_SRC], 3, 0}
};


#endif /* LXB_DOM_ATTR_RES_H */
