/*
 * Copyright (C) 2019-2020 Alexander Borisov
 *
 * Author: Alexander Borisov <borisov@lexbor.com>
 */

/*
 * Caution!
 * This file generated by the script "utils/lexbor/dom/attr.py"!
 * Do not change this file!
 */


#ifndef LXB_DOM_ATTR_CONST_H
#define LXB_DOM_ATTR_CONST_H


typedef uintptr_t lxb_dom_attr_id_t;

typedef enum {
    LXB_DOM_ATTR__UNDEF         = 0x0000,
    LXB_DOM_ATTR_ACCEPT         = 0x0001,
    LXB_DOM_ATTR_ACCEPT_CHARSET = 0x0002,
    LXB_DOM_ATTR_ACTIVE         = 0x0003,
    LXB_DOM_ATTR_ALIGN          = 0x0004,
    LXB_DOM_ATTR_ALINK          = 0x0005,
    LXB_DOM_ATTR_ALT            = 0x0006,
    LXB_DOM_ATTR_AXIS           = 0x0007,
    LXB_DOM_ATTR_BGCOLOR        = 0x0008,
    LXB_DOM_ATTR_CHARSET        = 0x0009,
    LXB_DOM_ATTR_CHECKED        = 0x000a,
    LXB_DOM_ATTR_CLASS          = 0x000b,
    LXB_DOM_ATTR_CLEAR          = 0x000c,
    LXB_DOM_ATTR_CODETYPE       = 0x000d,
    LXB_DOM_ATTR_COLOR          = 0x000e,
    LXB_DOM_ATTR_COMPACT        = 0x000f,
    LXB_DOM_ATTR_CONTENT        = 0x0010,
    LXB_DOM_ATTR_DECLARE        = 0x0011,
    LXB_DOM_ATTR_DEFER          = 0x0012,
    LXB_DOM_ATTR_DIR            = 0x0013,
    LXB_DOM_ATTR_DIRECTION      = 0x0014,
    LXB_DOM_ATTR_DISABLED       = 0x0015,
    LXB_DOM_ATTR_ENCTYPE        = 0x0016,
    LXB_DOM_ATTR_FACE           = 0x0017,
    LXB_DOM_ATTR_FOCUS          = 0x0018,
    LXB_DOM_ATTR_FOR            = 0x0019,
    LXB_DOM_ATTR_FRAME          = 0x001a,
    LXB_DOM_ATTR_HEIGHT         = 0x001b,
    LXB_DOM_ATTR_HOVER          = 0x001c,
    LXB_DOM_ATTR_HREF           = 0x001d,
    LXB_DOM_ATTR_HREFLANG       = 0x001e,
    LXB_DOM_ATTR_HTML           = 0x001f,
    LXB_DOM_ATTR_HTTP_EQUIV     = 0x0020,
    LXB_DOM_ATTR_ID             = 0x0021,
    LXB_DOM_ATTR_IS             = 0x0022,
    LXB_DOM_ATTR_LANG           = 0x0023,
    LXB_DOM_ATTR_LANGUAGE       = 0x0024,
    LXB_DOM_ATTR_LINK           = 0x0025,
    LXB_DOM_ATTR_MAXLENGTH      = 0x0026,
    LXB_DOM_ATTR_MEDIA          = 0x0027,
    LXB_DOM_ATTR_METHOD         = 0x0028,
    LXB_DOM_ATTR_MULTIPLE       = 0x0029,
    LXB_DOM_ATTR_NOHREF         = 0x002a,
    LXB_DOM_ATTR_NORESIZE       = 0x002b,
    LXB_DOM_ATTR_NOSHADE        = 0x002c,
    LXB_DOM_ATTR_NOWRAP         = 0x002d,
    LXB_DOM_ATTR_PLACEHOLDER    = 0x002e,
    LXB_DOM_ATTR_POOL           = 0x002f,
    LXB_DOM_ATTR_PUBLIC         = 0x0030,
    LXB_DOM_ATTR_READONLY       = 0x0031,
    LXB_DOM_ATTR_REL            = 0x0032,
    LXB_DOM_ATTR_REQUIRED       = 0x0033,
    LXB_DOM_ATTR_REV            = 0x0034,
    LXB_DOM_ATTR_RULES          = 0x0035,
    LXB_DOM_ATTR_SCHEME         = 0x0036,
    LXB_DOM_ATTR_SCOPE          = 0x0037,
    LXB_DOM_ATTR_SCROLLING      = 0x0038,
    LXB_DOM_ATTR_SELECTED       = 0x0039,
    LXB_DOM_ATTR_SHAPE          = 0x003a,
    LXB_DOM_ATTR_SIZE           = 0x003b,
    LXB_DOM_ATTR_SLOT           = 0x003c,
    LXB_DOM_ATTR_SRC            = 0x003d,
    LXB_DOM_ATTR_STYLE          = 0x003e,
    LXB_DOM_ATTR_SYSTEM         = 0x003f,
    LXB_DOM_ATTR_TARGET         = 0x0040,
    LXB_DOM_ATTR_TEXT           = 0x0041,
    LXB_DOM_ATTR_TITLE          = 0x0042,
    LXB_DOM_ATTR_TYPE           = 0x0043,
    LXB_DOM_ATTR_VALIGN         = 0x0044,
    LXB_DOM_ATTR_VALUETYPE      = 0x0045,
    LXB_DOM_ATTR_VLINK          = 0x0046,
    LXB_DOM_ATTR_WIDTH          = 0x0047,
    LXB_DOM_ATTR_XMLNS          = 0x0048,
    LXB_DOM_ATTR__LAST_ENTRY    = 0x0049
}
lxb_dom_attr_id_enum_t;


#endif /* LXB_DOM_ATTR_CONST_H */
