/*
 * Copyright (C) 2019-2020 Alexander Borisov
 *
 * Author: Alexander Borisov <borisov@lexbor.com>
 */

/*
 * Caution!
 * This file generated by the script "utils/lexbor/dom/attr.py"!
 * Do not change this file!
 */


#ifndef LXB_DOM_ATTR_CONST_H
#define LXB_DOM_ATTR_CONST_H


typedef uintptr_t lxb_dom_attr_id_t;

%%BODY%%


#endif /* LXB_DOM_ATTR_CONST_H */
