/*
 * Copyright (C) 2019-2020 Alexander Borisov
 *
 * Author: Alexander Borisov <borisov@lexbor.com>
 */

/*
 * Caution!
 * This file generated by the script "utils/lexbor/dom/attr.py"!
 * Do not change this file!
 */


#ifndef LXB_DOM_ATTR_RES_H
#define LXB_DOM_ATTR_RES_H

#include "lexbor/core/shs.h"

#include "lexbor/dom/interfaces/attr_const.h"


%%SHS_DATA%%

%%SHS%%


#endif /* LXB_DOM_ATTR_RES_H */
