ascii_names_map = [
    ['NUL', 'NULL'],
    ['SOH', 'Start of Heading'],
    ['STX', 'Start of text'],
    ['ETX', 'End of text'],
    ['EOT', 'End of Transmission'],
    ['ENQ', 'Enquiry'],
    ['ACK', 'Acknowledge'],
    ['BEL', 'Bell'],
    ['BS', 'Backspace'],
    ['TAB', 'Horizontal Tab'],
    ['LF', 'Line Feed (\'\\n\')'],
    ['VT', 'Vertical Tab'],
    ['FF', 'Form Feed'],
    ['CR', 'Carriage Return (\'\\r\')'],
    ['SO', 'Shift Out'],
    ['SI', 'Shift In'],
    ['DLE', 'Data Link Escape'],
    ['DC1', 'Device Control #1'],
    ['DC2', 'Device Control #2'],
    ['DC3', 'Device Control #3'],
    ['DC4', 'Device Control #4'],
    ['NAK', 'Negative Acknowledge'],
    ['SYN', 'Synchronous Idle'],
    ['ETB', 'End of Transmission Block'],
    ['CAN', 'Cancel'],
    ['EM', 'End of Medium'],
    ['SUB', 'Substitute'],
    ['ESC', 'Escape'],
    ['FS', 'File Separator'],
    ['GS', 'Group Separator'],
    ['RS', 'Record Separator'],
    ['US', 'Unit Separator'],
    ['SP', 'Space'],
    ['!', 'Exclamation mark'],
    ['"', 'Only quotes above'],
    ['#', 'Pound sign'],
    ['$', 'Dollar sign'],
    ['%', 'Percentage sign'],
    ['&', 'Commericial and'],
    ['\'', 'Apostrophe'],
    ['(', 'Left bracket'],
    [')', 'Right bracket'],
    ['*', 'Asterisk'],
    ['+', 'Plus symbol'],
    [',', 'Comma'],
    ['-', 'Dash'],
    ['.', 'Full stop'],
    ['/', 'Forward slash'],
    ['0', None],
    ['1', None],
    ['2', None],
    ['3', None],
    ['4', None],
    ['5', None],
    ['6', None],
    ['7', None],
    ['8', None],
    ['9', None],
    [':', 'Colon'],
    [';', 'Semicolon'],
    ['<', 'Small than bracket'],
    ['=', 'Equals sign'],
    ['>', 'Bigger than symbol'],
    ['?', 'Question mark'],
    ['@', 'At symbol'],
    ['A', None],
    ['B', None],
    ['C', None],
    ['D', None],
    ['E', None],
    ['F', None],
    ['G', None],
    ['H', None],
    ['I', None],
    ['J', None],
    ['K', None],
    ['L', None],
    ['M', None],
    ['N', None],
    ['O', None],
    ['P', None],
    ['Q', None],
    ['R', None],
    ['S', None],
    ['T', None],
    ['U', None],
    ['V', None],
    ['W', None],
    ['X', None],
    ['Y', None],
    ['Z', None],
    ['[', 'Left square bracket'],
    ['\\', 'Inverse/backward slash'],
    [']', 'Right square bracket'],
    ['^', 'Circumflex'],
    ['_', 'Underscore'],
    ['`', 'Gravis (backtick)'],
    ['a', None],
    ['b', None],
    ['c', None],
    ['d', None],
    ['e', None],
    ['f', None],
    ['g', None],
    ['h', None],
    ['i', None],
    ['j', None],
    ['k', None],
    ['l', None],
    ['m', None],
    ['n', None],
    ['o', None],
    ['p', None],
    ['q', None],
    ['r', None],
    ['s', None],
    ['t', None],
    ['u', None],
    ['v', None],
    ['w', None],
    ['x', None],
    ['y', None],
    ['z', None],
    ['{', 'Left curly bracket'],
    ['|', 'Vertical line'],
    ['}', 'Right curly brackets'],
    ['~', 'Tilde'],
    ['DEL', 'Delete'] # Last entry: 7F (127)
]