/*
 * Copyright (C) 2022 Alexander Borisov
 *
 * Author: Alexander Borisov <borisov@lexbor.com>
 */

/*
 * Caution!
 * This file generated by the script "utils/lexbor/css/names.py"!
 * Do not change this file!
 */


#ifndef LXB_CSS_PROPERTY_CONST_H
#define LXB_CSS_PROPERTY_CONST_H


#include "lexbor/css/value/const.h"


enum {
    LXB_CSS_PROPERTY__UNDEF      = 0x0000,
    LXB_CSS_PROPERTY__CUSTOM     = 0x0001,
    LXB_CSS_PROPERTY_HEIGHT      = 0x0002,
    LXB_CSS_PROPERTY_WIDTH       = 0x0003,
    LXB_CSS_PROPERTY__LAST_ENTRY = 0x0004
};
typedef uintptr_t lxb_css_property_type_t;

enum {
    LXB_CSS_HEIGHT_AUTO        = LXB_CSS_VALUE_AUTO,
    LXB_CSS_HEIGHT_MIN_CONTENT = LXB_CSS_VALUE_MIN_CONTENT,
    LXB_CSS_HEIGHT_MAX_CONTENT = LXB_CSS_VALUE_MAX_CONTENT,
    LXB_CSS_HEIGHT__LENGTH     = LXB_CSS_VALUE__LENGTH,
    LXB_CSS_HEIGHT__PERCENTAGE = LXB_CSS_VALUE__PERCENTAGE
};
typedef unsigned int lxb_css_height_type_t;

enum {
    LXB_CSS_WIDTH_AUTO        = LXB_CSS_VALUE_AUTO,
    LXB_CSS_WIDTH_MIN_CONTENT = LXB_CSS_VALUE_MIN_CONTENT,
    LXB_CSS_WIDTH_MAX_CONTENT = LXB_CSS_VALUE_MAX_CONTENT,
    LXB_CSS_WIDTH__LENGTH     = LXB_CSS_VALUE__LENGTH,
    LXB_CSS_WIDTH__PERCENTAGE = LXB_CSS_VALUE__PERCENTAGE
};
typedef unsigned int lxb_css_width_type_t;


#endif /* LXB_CSS_PROPERTY_CONST_H */
