/*
 * Copyright (C) 2020-2021 Alexander Borisov
 *
 * Author: Alexander Borisov <borisov@lexbor.com>
 */

/*
 * Caution!
 * This file generated by the script "utils/lexbor/css/selectors/pseudo.py"!
 * Do not change this file!
 */


#ifndef LXB_CSS_SELECTOS_PSEUDO_CONST_H
#define LXB_CSS_SELECTOS_PSEUDO_CONST_H


%%BODY%%


#endif /* LXB_CSS_SELECTOS_PSEUDO_CONST_H */
