/*
 * Copyright (C) 2020-2021 Alexander Borisov
 *
 * Author: Alexander Borisov <borisov@lexbor.com>
 */

/*
 * Caution!
 * This file generated by the script "utils/lexbor/css/selectors/pseudo.py"!
 * Do not change this file!
 */


#ifndef LXB_CSS_SELECTOS_PSEUDO_RES_H
#define LXB_CSS_SELECTOS_PSEUDO_RES_H

#include "lexbor/core/shs.h"
#include "lexbor/css/selectors/pseudo_const.h"


%%SHS_DATA%%

%%SHS%%


#endif /* LXB_CSS_SELECTOS_PSEUDO_RES_H */
