/*
 * Copyright (C) 2018 Alexander Borisov
 *
 * Author: Alexander Borisov <lex.borisov@gmail.com>
 */

/*
 * Caution!!! Important!!!
 * This file is generated by the script "utils/lexbor/html/tags.py"!
 * Do not change this file!
 */


#include <unit/test.h>

#include <lexbor/html/ns.h>


TEST_BEGIN(names)
{
    const lxb_html_ns_data_t *entry;

    entry = lxb_html_ns_data_by_name((const lxb_char_t *) "-UNDEF", 6);
    test_ne(entry, NULL); test_eq_str(entry->name, "-undef");
    entry = lxb_html_ns_data_by_name((const lxb_char_t *) "-ANY", 4);
    test_ne(entry, NULL); test_eq_str(entry->name, "-any");
    entry = lxb_html_ns_data_by_name((const lxb_char_t *) "HTML", 4);
    test_ne(entry, NULL); test_eq_str(entry->name, "HTML");
    entry = lxb_html_ns_data_by_name((const lxb_char_t *) "MATHML", 6);
    test_ne(entry, NULL); test_eq_str(entry->name, "MathML");
    entry = lxb_html_ns_data_by_name((const lxb_char_t *) "SVG", 3);
    test_ne(entry, NULL); test_eq_str(entry->name, "SVG");
    entry = lxb_html_ns_data_by_name((const lxb_char_t *) "XLINK", 5);
    test_ne(entry, NULL); test_eq_str(entry->name, "XLink");
    entry = lxb_html_ns_data_by_name((const lxb_char_t *) "XML", 3);
    test_ne(entry, NULL); test_eq_str(entry->name, "XML");
    entry = lxb_html_ns_data_by_name((const lxb_char_t *) "XMLNS", 5);
    test_ne(entry, NULL); test_eq_str(entry->name, "XMLNS");
}
TEST_END

int
main(int argc, const char * argv[])
{
    TEST_INIT();

    TEST_ADD(names);

    TEST_RUN("lexbor/html/ns_res");
    TEST_RELEASE();
}


