/*
 * Copyright (C) %%YEAR%% Alexander Borisov
 *
 * Author: Alexander Borisov <borisov@lexbor.com>
 */

/*
 * Caution!
 * This file generated by the script "utils/lexbor/css/names.py"!
 * Do not change this file!
 */


#ifndef LXB_CSS_%%PREFIX%%_CONST_H
#define LXB_CSS_%%PREFIX%%_CONST_H


#include "lexbor/css/value/const.h"


%%BODY%%


#endif /* LXB_CSS_%%PREFIX%%_CONST_H */
