/*
 * Copyright (C) %%YEAR%% Alexander Borisov
 *
 * Author: Alexander Borisov <borisov@lexbor.com>
 */

/*
 * Caution!
 * This file generated by the script "utils/lexbor/css/names.py"!
 * Do not change this file!
 */


#ifndef LXB_CSS_%%PREFIX%%_RES_H
#define LXB_CSS_%%PREFIX%%_RES_H

#include "lexbor/core/shs.h"
#include "%%HEADER%%"


%%SHS_DATA%%

%%SHS%%


#endif /* LXB_CSS_%%PREFIX%%_RES_H */
