/*
 * Copyright (C) 2018 Alexander Borisov
 *
 * Author: Alexander Borisov <borisov@lexbor.com>
 */

/*
 * Caution!
 * This file is generated by the script "utils/lexbor/tag_ns/tags.py"!
 * Do not change this file!
 */


#include <unit/test.h>

#include <lexbor/ns/ns.h>


TEST_BEGIN(names)
{
    const lxb_ns_data_t *entry;
    lexbor_hash_t *ns;

    ns = lexbor_hash_create();
    test_eq(lexbor_hash_init(ns, 32, sizeof(lxb_ns_data_t)), LXB_STATUS_OK);

%%TEST_NAMES%%

    lexbor_hash_destroy(ns, true);
}
TEST_END

int
main(int argc, const char * argv[])
{
    TEST_INIT();

    TEST_ADD(names);

    TEST_RUN("lexbor/ns/res");
    TEST_RELEASE();
}


