/*
 * Copyright (C) 2018 Alexander Borisov
 *
 * Author: Alexander Borisov <borisov@lexbor.com>
 */

/*
 * Caution!
 * This file is generated by the script "utils/lexbor/tag_ns/tags.py"!
 * Do not change this file!
 */


#include <unit/test.h>

#include <lexbor/tag/tag.h>

#define LXB_HTML_TAG_RES_DATA
#define LXB_HTML_TAG_RES_SHS_DATA
#include <lexbor/html/tag_res.h>


TEST_BEGIN(names)
{
    const lxb_tag_data_t *entry;
    lexbor_hash_t *tags;

    tags = lexbor_hash_create();
    test_eq(lexbor_hash_init(tags, 32, sizeof(lxb_tag_data_t)), LXB_STATUS_OK);

%%TEST_NAMES%%

    lexbor_hash_destroy(tags, true);
}
TEST_END

int
main(int argc, const char * argv[])
{
    TEST_INIT();

    TEST_ADD(names);

    TEST_RUN("lexbor/tag/res");
    TEST_RELEASE();
}


