set(DEPENDENCIES "")

# For LEXBOR_BUILD_SEPARATELY is ON
IF(TARGET ${CURRENT_LIB_NAME})
    FEATURE_TRY_FUNCTION_EXISTS("${CURRENT_LIB_NAME}" "ceil" "m")
ENDIF()
IF(TARGET ${CURRENT_LIB_NAME_STATIC})
    FEATURE_TRY_FUNCTION_EXISTS("${CURRENT_LIB_NAME_STATIC}" "ceil" "m")
ENDIF()

# For LEXBOR_BUILD_SEPARATELY is OFF
IF(TARGET ${LEXBOR_LIB_NAME})
    FEATURE_TRY_FUNCTION_EXISTS("${LEXBOR_LIB_NAME}" "ceil" "m")
ENDIF()
IF(TARGET ${CURRENT_LIB_NAME_STATIC})
    FEATURE_TRY_FUNCTION_EXISTS("${CURRENT_LIB_NAME_STATIC}" "ceil" "m")
ENDIF()
