/*
 * Copyright (C) 2022 Alexander Borisov
 *
 * Author: Alexander Borisov <borisov@lexbor.com>
 */

/*
 * Caution!
 * This file generated by the script "utils/lexbor/css/names.py"!
 * Do not change this file!
 */


#ifndef LXB_CSS_VALUE_CONST_H
#define LXB_CSS_VALUE_CONST_H


enum {
    LXB_CSS_VALUE__UNDEF      = 0x0000,
    LXB_CSS_VALUE_INITIAL     = 0x0001,
    LXB_CSS_VALUE_INHERIT     = 0x0002,
    LXB_CSS_VALUE_UNSET       = 0x0003,
    LXB_CSS_VALUE_REVERT      = 0x0004,
    LXB_CSS_VALUE_AUTO        = 0x0005,
    LXB_CSS_VALUE_MIN_CONTENT = 0x0006,
    LXB_CSS_VALUE_MAX_CONTENT = 0x0007,
    LXB_CSS_VALUE__LENGTH     = 0x0008,
    LXB_CSS_VALUE__PERCENTAGE = 0x0009,
    LXB_CSS_VALUE__LAST_ENTRY = 0x000a
};
typedef unsigned int lxb_css_value_type_t;


#endif /* LXB_CSS_VALUE_CONST_H */
