/*
 * Copyright (C) 2018-2026 Alexander Borisov
 *
 * Author: Alexander Borisov <borisov@lexbor.com>
 */

/*
 * Caution!
 * This file generated by the script "utils/lexbor/tag_ns/tags.py"!
 * Do not change this file!
 */


#ifndef LXB_STYLE_OPEN_ELEMENTS_RES_H
#define LXB_STYLE_OPEN_ELEMENTS_RES_H

#ifdef LXB_TAG_CONST_VERSION
#ifndef LXB_TAG_CONST_VERSION_5AB3094FB370521074947DC082575715
#error Mismatched tags version! See "lexbor/tag/const.h".
#endif /* LXB_TAG_CONST_VERSION_5AB3094FB370521074947DC082575715 */
#else
#error You need to include "lexbor/tag/const.h".
#endif /* LXB_TAG_CONST_VERSION */

static const lxb_html_document_open_elements_pop_f lxb_style_tree_open_elements_pop_res[LXB_TAG__LAST_ENTRY] = 
{
    /* LXB_TAG__UNDEF */
    NULL,
    /* LXB_TAG__END_OF_FILE */
    NULL,
    /* LXB_TAG__TEXT */
    NULL,
    /* LXB_TAG__DOCUMENT */
    NULL,
    /* LXB_TAG__EM_COMMENT */
    NULL,
    /* LXB_TAG__EM_DOCTYPE */
    NULL,
    /* LXB_TAG_A */
    NULL,
    /* LXB_TAG_ABBR */
    NULL,
    /* LXB_TAG_ACRONYM */
    NULL,
    /* LXB_TAG_ADDRESS */
    NULL,
    /* LXB_TAG_ALTGLYPH */
    NULL,
    /* LXB_TAG_ALTGLYPHDEF */
    NULL,
    /* LXB_TAG_ALTGLYPHITEM */
    NULL,
    /* LXB_TAG_ANIMATECOLOR */
    NULL,
    /* LXB_TAG_ANIMATEMOTION */
    NULL,
    /* LXB_TAG_ANIMATETRANSFORM */
    NULL,
    /* LXB_TAG_ANNOTATION_XML */
    NULL,
    /* LXB_TAG_APPLET */
    NULL,
    /* LXB_TAG_AREA */
    NULL,
    /* LXB_TAG_ARTICLE */
    NULL,
    /* LXB_TAG_ASIDE */
    NULL,
    /* LXB_TAG_AUDIO */
    NULL,
    /* LXB_TAG_B */
    NULL,
    /* LXB_TAG_BASE */
    NULL,
    /* LXB_TAG_BASEFONT */
    NULL,
    /* LXB_TAG_BDI */
    NULL,
    /* LXB_TAG_BDO */
    NULL,
    /* LXB_TAG_BGSOUND */
    NULL,
    /* LXB_TAG_BIG */
    NULL,
    /* LXB_TAG_BLINK */
    NULL,
    /* LXB_TAG_BLOCKQUOTE */
    NULL,
    /* LXB_TAG_BODY */
    NULL,
    /* LXB_TAG_BR */
    NULL,
    /* LXB_TAG_BUTTON */
    NULL,
    /* LXB_TAG_CANVAS */
    NULL,
    /* LXB_TAG_CAPTION */
    NULL,
    /* LXB_TAG_CENTER */
    NULL,
    /* LXB_TAG_CITE */
    NULL,
    /* LXB_TAG_CLIPPATH */
    NULL,
    /* LXB_TAG_CODE */
    NULL,
    /* LXB_TAG_COL */
    NULL,
    /* LXB_TAG_COLGROUP */
    NULL,
    /* LXB_TAG_DATA */
    NULL,
    /* LXB_TAG_DATALIST */
    NULL,
    /* LXB_TAG_DD */
    NULL,
    /* LXB_TAG_DEL */
    NULL,
    /* LXB_TAG_DESC */
    NULL,
    /* LXB_TAG_DETAILS */
    NULL,
    /* LXB_TAG_DFN */
    NULL,
    /* LXB_TAG_DIALOG */
    NULL,
    /* LXB_TAG_DIR */
    NULL,
    /* LXB_TAG_DIV */
    NULL,
    /* LXB_TAG_DL */
    NULL,
    /* LXB_TAG_DT */
    NULL,
    /* LXB_TAG_EM */
    NULL,
    /* LXB_TAG_EMBED */
    NULL,
    /* LXB_TAG_FEBLEND */
    NULL,
    /* LXB_TAG_FECOLORMATRIX */
    NULL,
    /* LXB_TAG_FECOMPONENTTRANSFER */
    NULL,
    /* LXB_TAG_FECOMPOSITE */
    NULL,
    /* LXB_TAG_FECONVOLVEMATRIX */
    NULL,
    /* LXB_TAG_FEDIFFUSELIGHTING */
    NULL,
    /* LXB_TAG_FEDISPLACEMENTMAP */
    NULL,
    /* LXB_TAG_FEDISTANTLIGHT */
    NULL,
    /* LXB_TAG_FEDROPSHADOW */
    NULL,
    /* LXB_TAG_FEFLOOD */
    NULL,
    /* LXB_TAG_FEFUNCA */
    NULL,
    /* LXB_TAG_FEFUNCB */
    NULL,
    /* LXB_TAG_FEFUNCG */
    NULL,
    /* LXB_TAG_FEFUNCR */
    NULL,
    /* LXB_TAG_FEGAUSSIANBLUR */
    NULL,
    /* LXB_TAG_FEIMAGE */
    NULL,
    /* LXB_TAG_FEMERGE */
    NULL,
    /* LXB_TAG_FEMERGENODE */
    NULL,
    /* LXB_TAG_FEMORPHOLOGY */
    NULL,
    /* LXB_TAG_FEOFFSET */
    NULL,
    /* LXB_TAG_FEPOINTLIGHT */
    NULL,
    /* LXB_TAG_FESPECULARLIGHTING */
    NULL,
    /* LXB_TAG_FESPOTLIGHT */
    NULL,
    /* LXB_TAG_FETILE */
    NULL,
    /* LXB_TAG_FETURBULENCE */
    NULL,
    /* LXB_TAG_FIELDSET */
    NULL,
    /* LXB_TAG_FIGCAPTION */
    NULL,
    /* LXB_TAG_FIGURE */
    NULL,
    /* LXB_TAG_FONT */
    NULL,
    /* LXB_TAG_FOOTER */
    NULL,
    /* LXB_TAG_FOREIGNOBJECT */
    NULL,
    /* LXB_TAG_FORM */
    NULL,
    /* LXB_TAG_FRAME */
    NULL,
    /* LXB_TAG_FRAMESET */
    NULL,
    /* LXB_TAG_GLYPHREF */
    NULL,
    /* LXB_TAG_H1 */
    NULL,
    /* LXB_TAG_H2 */
    NULL,
    /* LXB_TAG_H3 */
    NULL,
    /* LXB_TAG_H4 */
    NULL,
    /* LXB_TAG_H5 */
    NULL,
    /* LXB_TAG_H6 */
    NULL,
    /* LXB_TAG_HEAD */
    NULL,
    /* LXB_TAG_HEADER */
    NULL,
    /* LXB_TAG_HGROUP */
    NULL,
    /* LXB_TAG_HR */
    NULL,
    /* LXB_TAG_HTML */
    NULL,
    /* LXB_TAG_I */
    NULL,
    /* LXB_TAG_IFRAME */
    NULL,
    /* LXB_TAG_IMAGE */
    NULL,
    /* LXB_TAG_IMG */
    NULL,
    /* LXB_TAG_INPUT */
    NULL,
    /* LXB_TAG_INS */
    NULL,
    /* LXB_TAG_ISINDEX */
    NULL,
    /* LXB_TAG_KBD */
    NULL,
    /* LXB_TAG_KEYGEN */
    NULL,
    /* LXB_TAG_LABEL */
    NULL,
    /* LXB_TAG_LEGEND */
    NULL,
    /* LXB_TAG_LI */
    NULL,
    /* LXB_TAG_LINEARGRADIENT */
    NULL,
    /* LXB_TAG_LINK */
    NULL,
    /* LXB_TAG_LISTING */
    NULL,
    /* LXB_TAG_MAIN */
    NULL,
    /* LXB_TAG_MALIGNMARK */
    NULL,
    /* LXB_TAG_MAP */
    NULL,
    /* LXB_TAG_MARK */
    NULL,
    /* LXB_TAG_MARQUEE */
    NULL,
    /* LXB_TAG_MATH */
    NULL,
    /* LXB_TAG_MENU */
    NULL,
    /* LXB_TAG_META */
    NULL,
    /* LXB_TAG_METER */
    NULL,
    /* LXB_TAG_MFENCED */
    NULL,
    /* LXB_TAG_MGLYPH */
    NULL,
    /* LXB_TAG_MI */
    NULL,
    /* LXB_TAG_MN */
    NULL,
    /* LXB_TAG_MO */
    NULL,
    /* LXB_TAG_MS */
    NULL,
    /* LXB_TAG_MTEXT */
    NULL,
    /* LXB_TAG_MULTICOL */
    NULL,
    /* LXB_TAG_NAV */
    NULL,
    /* LXB_TAG_NEXTID */
    NULL,
    /* LXB_TAG_NOBR */
    NULL,
    /* LXB_TAG_NOEMBED */
    NULL,
    /* LXB_TAG_NOFRAMES */
    NULL,
    /* LXB_TAG_NOSCRIPT */
    NULL,
    /* LXB_TAG_OBJECT */
    NULL,
    /* LXB_TAG_OL */
    NULL,
    /* LXB_TAG_OPTGROUP */
    NULL,
    /* LXB_TAG_OPTION */
    lxb_html_option_element_pop_open_elements,
    /* LXB_TAG_OUTPUT */
    NULL,
    /* LXB_TAG_P */
    NULL,
    /* LXB_TAG_PARAM */
    NULL,
    /* LXB_TAG_PATH */
    NULL,
    /* LXB_TAG_PICTURE */
    NULL,
    /* LXB_TAG_PLAINTEXT */
    NULL,
    /* LXB_TAG_PRE */
    NULL,
    /* LXB_TAG_PROGRESS */
    NULL,
    /* LXB_TAG_Q */
    NULL,
    /* LXB_TAG_RADIALGRADIENT */
    NULL,
    /* LXB_TAG_RB */
    NULL,
    /* LXB_TAG_RP */
    NULL,
    /* LXB_TAG_RT */
    NULL,
    /* LXB_TAG_RTC */
    NULL,
    /* LXB_TAG_RUBY */
    NULL,
    /* LXB_TAG_S */
    NULL,
    /* LXB_TAG_SAMP */
    NULL,
    /* LXB_TAG_SCRIPT */
    NULL,
    /* LXB_TAG_SEARCH */
    NULL,
    /* LXB_TAG_SECTION */
    NULL,
    /* LXB_TAG_SELECT */
    NULL,
    /* LXB_TAG_SELECTEDCONTENT */
    NULL,
    /* LXB_TAG_SLOT */
    NULL,
    /* LXB_TAG_SMALL */
    NULL,
    /* LXB_TAG_SOURCE */
    NULL,
    /* LXB_TAG_SPACER */
    NULL,
    /* LXB_TAG_SPAN */
    NULL,
    /* LXB_TAG_STRIKE */
    NULL,
    /* LXB_TAG_STRONG */
    NULL,
    /* LXB_TAG_STYLE */
    lxb_html_style_element_pop_open_elements,
    /* LXB_TAG_SUB */
    NULL,
    /* LXB_TAG_SUMMARY */
    NULL,
    /* LXB_TAG_SUP */
    NULL,
    /* LXB_TAG_SVG */
    NULL,
    /* LXB_TAG_TABLE */
    NULL,
    /* LXB_TAG_TBODY */
    NULL,
    /* LXB_TAG_TD */
    NULL,
    /* LXB_TAG_TEMPLATE */
    NULL,
    /* LXB_TAG_TEXTAREA */
    NULL,
    /* LXB_TAG_TEXTPATH */
    NULL,
    /* LXB_TAG_TFOOT */
    NULL,
    /* LXB_TAG_TH */
    NULL,
    /* LXB_TAG_THEAD */
    NULL,
    /* LXB_TAG_TIME */
    NULL,
    /* LXB_TAG_TITLE */
    NULL,
    /* LXB_TAG_TR */
    NULL,
    /* LXB_TAG_TRACK */
    NULL,
    /* LXB_TAG_TT */
    NULL,
    /* LXB_TAG_U */
    NULL,
    /* LXB_TAG_UL */
    NULL,
    /* LXB_TAG_VAR */
    NULL,
    /* LXB_TAG_VIDEO */
    NULL,
    /* LXB_TAG_WBR */
    NULL,
    /* LXB_TAG_XMP */
    NULL
};

#endif /* LXB_STYLE_OPEN_ELEMENTS_RES_H */
