/*
 * Copyright (C) 2018-2026 Alexander Borisov
 *
 * Author: Alexander Borisov <borisov@lexbor.com>
 */

/*
 * Caution!
 * This file generated by the script "utils/lexbor/tag_ns/tags.py"!
 * Do not change this file!
 */


#ifndef LXB_HTML_ELEMENT_STEPS_RES_H
#define LXB_HTML_ELEMENT_STEPS_RES_H

#ifdef LXB_TAG_CONST_VERSION
#ifndef LXB_TAG_CONST_VERSION_5AB3094FB370521074947DC082575715
#error Mismatched tags version! See "lexbor/tag/const.h".
#endif /* LXB_TAG_CONST_VERSION_5AB3094FB370521074947DC082575715 */
#else
#error You need to include "lexbor/tag/const.h".
#endif /* LXB_TAG_CONST_VERSION */

static const lxb_dom_document_mutation_cb_t lxb_html_element_steps_res_default[LXB_TAG__LAST_ENTRY] = 
{
    /* LXB_TAG__UNDEF */
    {.inserted = NULL, .removed = NULL, .moved = NULL, .destroy = NULL, .children_changed = NULL, .connected = NULL},
    /* LXB_TAG__END_OF_FILE */
    {.inserted = NULL, .removed = NULL, .moved = NULL, .destroy = NULL, .children_changed = NULL, .connected = NULL},
    /* LXB_TAG__TEXT */
    {.inserted = NULL, .removed = NULL, .moved = NULL, .destroy = NULL, .children_changed = NULL, .connected = NULL},
    /* LXB_TAG__DOCUMENT */
    {.inserted = NULL, .removed = NULL, .moved = NULL, .destroy = NULL, .children_changed = NULL, .connected = NULL},
    /* LXB_TAG__EM_COMMENT */
    {.inserted = NULL, .removed = NULL, .moved = NULL, .destroy = NULL, .children_changed = NULL, .connected = NULL},
    /* LXB_TAG__EM_DOCTYPE */
    {.inserted = NULL, .removed = NULL, .moved = NULL, .destroy = NULL, .children_changed = NULL, .connected = NULL},
    /* LXB_TAG_A */
    {.inserted = NULL, .removed = NULL, .moved = NULL, .destroy = NULL, .children_changed = NULL, .connected = NULL},
    /* LXB_TAG_ABBR */
    {.inserted = NULL, .removed = NULL, .moved = NULL, .destroy = NULL, .children_changed = NULL, .connected = NULL},
    /* LXB_TAG_ACRONYM */
    {.inserted = NULL, .removed = NULL, .moved = NULL, .destroy = NULL, .children_changed = NULL, .connected = NULL},
    /* LXB_TAG_ADDRESS */
    {.inserted = NULL, .removed = NULL, .moved = NULL, .destroy = NULL, .children_changed = NULL, .connected = NULL},
    /* LXB_TAG_ALTGLYPH */
    {.inserted = NULL, .removed = NULL, .moved = NULL, .destroy = NULL, .children_changed = NULL, .connected = NULL},
    /* LXB_TAG_ALTGLYPHDEF */
    {.inserted = NULL, .removed = NULL, .moved = NULL, .destroy = NULL, .children_changed = NULL, .connected = NULL},
    /* LXB_TAG_ALTGLYPHITEM */
    {.inserted = NULL, .removed = NULL, .moved = NULL, .destroy = NULL, .children_changed = NULL, .connected = NULL},
    /* LXB_TAG_ANIMATECOLOR */
    {.inserted = NULL, .removed = NULL, .moved = NULL, .destroy = NULL, .children_changed = NULL, .connected = NULL},
    /* LXB_TAG_ANIMATEMOTION */
    {.inserted = NULL, .removed = NULL, .moved = NULL, .destroy = NULL, .children_changed = NULL, .connected = NULL},
    /* LXB_TAG_ANIMATETRANSFORM */
    {.inserted = NULL, .removed = NULL, .moved = NULL, .destroy = NULL, .children_changed = NULL, .connected = NULL},
    /* LXB_TAG_ANNOTATION_XML */
    {.inserted = NULL, .removed = NULL, .moved = NULL, .destroy = NULL, .children_changed = NULL, .connected = NULL},
    /* LXB_TAG_APPLET */
    {.inserted = NULL, .removed = NULL, .moved = NULL, .destroy = NULL, .children_changed = NULL, .connected = NULL},
    /* LXB_TAG_AREA */
    {.inserted = NULL, .removed = NULL, .moved = NULL, .destroy = NULL, .children_changed = NULL, .connected = NULL},
    /* LXB_TAG_ARTICLE */
    {.inserted = NULL, .removed = NULL, .moved = NULL, .destroy = NULL, .children_changed = NULL, .connected = NULL},
    /* LXB_TAG_ASIDE */
    {.inserted = NULL, .removed = NULL, .moved = NULL, .destroy = NULL, .children_changed = NULL, .connected = NULL},
    /* LXB_TAG_AUDIO */
    {.inserted = NULL, .removed = NULL, .moved = NULL, .destroy = NULL, .children_changed = NULL, .connected = NULL},
    /* LXB_TAG_B */
    {.inserted = NULL, .removed = NULL, .moved = NULL, .destroy = NULL, .children_changed = NULL, .connected = NULL},
    /* LXB_TAG_BASE */
    {.inserted = NULL, .removed = NULL, .moved = NULL, .destroy = NULL, .children_changed = NULL, .connected = NULL},
    /* LXB_TAG_BASEFONT */
    {.inserted = NULL, .removed = NULL, .moved = NULL, .destroy = NULL, .children_changed = NULL, .connected = NULL},
    /* LXB_TAG_BDI */
    {.inserted = NULL, .removed = NULL, .moved = NULL, .destroy = NULL, .children_changed = NULL, .connected = NULL},
    /* LXB_TAG_BDO */
    {.inserted = NULL, .removed = NULL, .moved = NULL, .destroy = NULL, .children_changed = NULL, .connected = NULL},
    /* LXB_TAG_BGSOUND */
    {.inserted = NULL, .removed = NULL, .moved = NULL, .destroy = NULL, .children_changed = NULL, .connected = NULL},
    /* LXB_TAG_BIG */
    {.inserted = NULL, .removed = NULL, .moved = NULL, .destroy = NULL, .children_changed = NULL, .connected = NULL},
    /* LXB_TAG_BLINK */
    {.inserted = NULL, .removed = NULL, .moved = NULL, .destroy = NULL, .children_changed = NULL, .connected = NULL},
    /* LXB_TAG_BLOCKQUOTE */
    {.inserted = NULL, .removed = NULL, .moved = NULL, .destroy = NULL, .children_changed = NULL, .connected = NULL},
    /* LXB_TAG_BODY */
    {.inserted = NULL, .removed = NULL, .moved = NULL, .destroy = NULL, .children_changed = NULL, .connected = NULL},
    /* LXB_TAG_BR */
    {.inserted = NULL, .removed = NULL, .moved = NULL, .destroy = NULL, .children_changed = NULL, .connected = NULL},
    /* LXB_TAG_BUTTON */
    {.inserted = NULL, .removed = NULL, .moved = NULL, .destroy = NULL, .children_changed = NULL, .connected = NULL},
    /* LXB_TAG_CANVAS */
    {.inserted = NULL, .removed = NULL, .moved = NULL, .destroy = NULL, .children_changed = NULL, .connected = NULL},
    /* LXB_TAG_CAPTION */
    {.inserted = NULL, .removed = NULL, .moved = NULL, .destroy = NULL, .children_changed = NULL, .connected = NULL},
    /* LXB_TAG_CENTER */
    {.inserted = NULL, .removed = NULL, .moved = NULL, .destroy = NULL, .children_changed = NULL, .connected = NULL},
    /* LXB_TAG_CITE */
    {.inserted = NULL, .removed = NULL, .moved = NULL, .destroy = NULL, .children_changed = NULL, .connected = NULL},
    /* LXB_TAG_CLIPPATH */
    {.inserted = NULL, .removed = NULL, .moved = NULL, .destroy = NULL, .children_changed = NULL, .connected = NULL},
    /* LXB_TAG_CODE */
    {.inserted = NULL, .removed = NULL, .moved = NULL, .destroy = NULL, .children_changed = NULL, .connected = NULL},
    /* LXB_TAG_COL */
    {.inserted = NULL, .removed = NULL, .moved = NULL, .destroy = NULL, .children_changed = NULL, .connected = NULL},
    /* LXB_TAG_COLGROUP */
    {.inserted = NULL, .removed = NULL, .moved = NULL, .destroy = NULL, .children_changed = NULL, .connected = NULL},
    /* LXB_TAG_DATA */
    {.inserted = NULL, .removed = NULL, .moved = NULL, .destroy = NULL, .children_changed = NULL, .connected = NULL},
    /* LXB_TAG_DATALIST */
    {.inserted = NULL, .removed = NULL, .moved = NULL, .destroy = NULL, .children_changed = NULL, .connected = NULL},
    /* LXB_TAG_DD */
    {.inserted = NULL, .removed = NULL, .moved = NULL, .destroy = NULL, .children_changed = NULL, .connected = NULL},
    /* LXB_TAG_DEL */
    {.inserted = NULL, .removed = NULL, .moved = NULL, .destroy = NULL, .children_changed = NULL, .connected = NULL},
    /* LXB_TAG_DESC */
    {.inserted = NULL, .removed = NULL, .moved = NULL, .destroy = NULL, .children_changed = NULL, .connected = NULL},
    /* LXB_TAG_DETAILS */
    {.inserted = NULL, .removed = NULL, .moved = NULL, .destroy = NULL, .children_changed = NULL, .connected = NULL},
    /* LXB_TAG_DFN */
    {.inserted = NULL, .removed = NULL, .moved = NULL, .destroy = NULL, .children_changed = NULL, .connected = NULL},
    /* LXB_TAG_DIALOG */
    {.inserted = NULL, .removed = NULL, .moved = NULL, .destroy = NULL, .children_changed = NULL, .connected = NULL},
    /* LXB_TAG_DIR */
    {.inserted = NULL, .removed = NULL, .moved = NULL, .destroy = NULL, .children_changed = NULL, .connected = NULL},
    /* LXB_TAG_DIV */
    {.inserted = NULL, .removed = NULL, .moved = NULL, .destroy = NULL, .children_changed = NULL, .connected = NULL},
    /* LXB_TAG_DL */
    {.inserted = NULL, .removed = NULL, .moved = NULL, .destroy = NULL, .children_changed = NULL, .connected = NULL},
    /* LXB_TAG_DT */
    {.inserted = NULL, .removed = NULL, .moved = NULL, .destroy = NULL, .children_changed = NULL, .connected = NULL},
    /* LXB_TAG_EM */
    {.inserted = NULL, .removed = NULL, .moved = NULL, .destroy = NULL, .children_changed = NULL, .connected = NULL},
    /* LXB_TAG_EMBED */
    {.inserted = NULL, .removed = NULL, .moved = NULL, .destroy = NULL, .children_changed = NULL, .connected = NULL},
    /* LXB_TAG_FEBLEND */
    {.inserted = NULL, .removed = NULL, .moved = NULL, .destroy = NULL, .children_changed = NULL, .connected = NULL},
    /* LXB_TAG_FECOLORMATRIX */
    {.inserted = NULL, .removed = NULL, .moved = NULL, .destroy = NULL, .children_changed = NULL, .connected = NULL},
    /* LXB_TAG_FECOMPONENTTRANSFER */
    {.inserted = NULL, .removed = NULL, .moved = NULL, .destroy = NULL, .children_changed = NULL, .connected = NULL},
    /* LXB_TAG_FECOMPOSITE */
    {.inserted = NULL, .removed = NULL, .moved = NULL, .destroy = NULL, .children_changed = NULL, .connected = NULL},
    /* LXB_TAG_FECONVOLVEMATRIX */
    {.inserted = NULL, .removed = NULL, .moved = NULL, .destroy = NULL, .children_changed = NULL, .connected = NULL},
    /* LXB_TAG_FEDIFFUSELIGHTING */
    {.inserted = NULL, .removed = NULL, .moved = NULL, .destroy = NULL, .children_changed = NULL, .connected = NULL},
    /* LXB_TAG_FEDISPLACEMENTMAP */
    {.inserted = NULL, .removed = NULL, .moved = NULL, .destroy = NULL, .children_changed = NULL, .connected = NULL},
    /* LXB_TAG_FEDISTANTLIGHT */
    {.inserted = NULL, .removed = NULL, .moved = NULL, .destroy = NULL, .children_changed = NULL, .connected = NULL},
    /* LXB_TAG_FEDROPSHADOW */
    {.inserted = NULL, .removed = NULL, .moved = NULL, .destroy = NULL, .children_changed = NULL, .connected = NULL},
    /* LXB_TAG_FEFLOOD */
    {.inserted = NULL, .removed = NULL, .moved = NULL, .destroy = NULL, .children_changed = NULL, .connected = NULL},
    /* LXB_TAG_FEFUNCA */
    {.inserted = NULL, .removed = NULL, .moved = NULL, .destroy = NULL, .children_changed = NULL, .connected = NULL},
    /* LXB_TAG_FEFUNCB */
    {.inserted = NULL, .removed = NULL, .moved = NULL, .destroy = NULL, .children_changed = NULL, .connected = NULL},
    /* LXB_TAG_FEFUNCG */
    {.inserted = NULL, .removed = NULL, .moved = NULL, .destroy = NULL, .children_changed = NULL, .connected = NULL},
    /* LXB_TAG_FEFUNCR */
    {.inserted = NULL, .removed = NULL, .moved = NULL, .destroy = NULL, .children_changed = NULL, .connected = NULL},
    /* LXB_TAG_FEGAUSSIANBLUR */
    {.inserted = NULL, .removed = NULL, .moved = NULL, .destroy = NULL, .children_changed = NULL, .connected = NULL},
    /* LXB_TAG_FEIMAGE */
    {.inserted = NULL, .removed = NULL, .moved = NULL, .destroy = NULL, .children_changed = NULL, .connected = NULL},
    /* LXB_TAG_FEMERGE */
    {.inserted = NULL, .removed = NULL, .moved = NULL, .destroy = NULL, .children_changed = NULL, .connected = NULL},
    /* LXB_TAG_FEMERGENODE */
    {.inserted = NULL, .removed = NULL, .moved = NULL, .destroy = NULL, .children_changed = NULL, .connected = NULL},
    /* LXB_TAG_FEMORPHOLOGY */
    {.inserted = NULL, .removed = NULL, .moved = NULL, .destroy = NULL, .children_changed = NULL, .connected = NULL},
    /* LXB_TAG_FEOFFSET */
    {.inserted = NULL, .removed = NULL, .moved = NULL, .destroy = NULL, .children_changed = NULL, .connected = NULL},
    /* LXB_TAG_FEPOINTLIGHT */
    {.inserted = NULL, .removed = NULL, .moved = NULL, .destroy = NULL, .children_changed = NULL, .connected = NULL},
    /* LXB_TAG_FESPECULARLIGHTING */
    {.inserted = NULL, .removed = NULL, .moved = NULL, .destroy = NULL, .children_changed = NULL, .connected = NULL},
    /* LXB_TAG_FESPOTLIGHT */
    {.inserted = NULL, .removed = NULL, .moved = NULL, .destroy = NULL, .children_changed = NULL, .connected = NULL},
    /* LXB_TAG_FETILE */
    {.inserted = NULL, .removed = NULL, .moved = NULL, .destroy = NULL, .children_changed = NULL, .connected = NULL},
    /* LXB_TAG_FETURBULENCE */
    {.inserted = NULL, .removed = NULL, .moved = NULL, .destroy = NULL, .children_changed = NULL, .connected = NULL},
    /* LXB_TAG_FIELDSET */
    {.inserted = NULL, .removed = NULL, .moved = NULL, .destroy = NULL, .children_changed = NULL, .connected = NULL},
    /* LXB_TAG_FIGCAPTION */
    {.inserted = NULL, .removed = NULL, .moved = NULL, .destroy = NULL, .children_changed = NULL, .connected = NULL},
    /* LXB_TAG_FIGURE */
    {.inserted = NULL, .removed = NULL, .moved = NULL, .destroy = NULL, .children_changed = NULL, .connected = NULL},
    /* LXB_TAG_FONT */
    {.inserted = NULL, .removed = NULL, .moved = NULL, .destroy = NULL, .children_changed = NULL, .connected = NULL},
    /* LXB_TAG_FOOTER */
    {.inserted = NULL, .removed = NULL, .moved = NULL, .destroy = NULL, .children_changed = NULL, .connected = NULL},
    /* LXB_TAG_FOREIGNOBJECT */
    {.inserted = NULL, .removed = NULL, .moved = NULL, .destroy = NULL, .children_changed = NULL, .connected = NULL},
    /* LXB_TAG_FORM */
    {.inserted = NULL, .removed = NULL, .moved = NULL, .destroy = NULL, .children_changed = NULL, .connected = NULL},
    /* LXB_TAG_FRAME */
    {.inserted = NULL, .removed = NULL, .moved = NULL, .destroy = NULL, .children_changed = NULL, .connected = NULL},
    /* LXB_TAG_FRAMESET */
    {.inserted = NULL, .removed = NULL, .moved = NULL, .destroy = NULL, .children_changed = NULL, .connected = NULL},
    /* LXB_TAG_GLYPHREF */
    {.inserted = NULL, .removed = NULL, .moved = NULL, .destroy = NULL, .children_changed = NULL, .connected = NULL},
    /* LXB_TAG_H1 */
    {.inserted = NULL, .removed = NULL, .moved = NULL, .destroy = NULL, .children_changed = NULL, .connected = NULL},
    /* LXB_TAG_H2 */
    {.inserted = NULL, .removed = NULL, .moved = NULL, .destroy = NULL, .children_changed = NULL, .connected = NULL},
    /* LXB_TAG_H3 */
    {.inserted = NULL, .removed = NULL, .moved = NULL, .destroy = NULL, .children_changed = NULL, .connected = NULL},
    /* LXB_TAG_H4 */
    {.inserted = NULL, .removed = NULL, .moved = NULL, .destroy = NULL, .children_changed = NULL, .connected = NULL},
    /* LXB_TAG_H5 */
    {.inserted = NULL, .removed = NULL, .moved = NULL, .destroy = NULL, .children_changed = NULL, .connected = NULL},
    /* LXB_TAG_H6 */
    {.inserted = NULL, .removed = NULL, .moved = NULL, .destroy = NULL, .children_changed = NULL, .connected = NULL},
    /* LXB_TAG_HEAD */
    {.inserted = NULL, .removed = NULL, .moved = NULL, .destroy = NULL, .children_changed = NULL, .connected = NULL},
    /* LXB_TAG_HEADER */
    {.inserted = NULL, .removed = NULL, .moved = NULL, .destroy = NULL, .children_changed = NULL, .connected = NULL},
    /* LXB_TAG_HGROUP */
    {.inserted = NULL, .removed = NULL, .moved = NULL, .destroy = NULL, .children_changed = NULL, .connected = NULL},
    /* LXB_TAG_HR */
    {.inserted = NULL, .removed = NULL, .moved = NULL, .destroy = NULL, .children_changed = NULL, .connected = NULL},
    /* LXB_TAG_HTML */
    {.inserted = NULL, .removed = NULL, .moved = NULL, .destroy = NULL, .children_changed = NULL, .connected = NULL},
    /* LXB_TAG_I */
    {.inserted = NULL, .removed = NULL, .moved = NULL, .destroy = NULL, .children_changed = NULL, .connected = NULL},
    /* LXB_TAG_IFRAME */
    {.inserted = NULL, .removed = NULL, .moved = NULL, .destroy = NULL, .children_changed = NULL, .connected = NULL},
    /* LXB_TAG_IMAGE */
    {.inserted = NULL, .removed = NULL, .moved = NULL, .destroy = NULL, .children_changed = NULL, .connected = NULL},
    /* LXB_TAG_IMG */
    {.inserted = NULL, .removed = NULL, .moved = NULL, .destroy = NULL, .children_changed = NULL, .connected = NULL},
    /* LXB_TAG_INPUT */
    {.inserted = NULL, .removed = NULL, .moved = NULL, .destroy = NULL, .children_changed = NULL, .connected = NULL},
    /* LXB_TAG_INS */
    {.inserted = NULL, .removed = NULL, .moved = NULL, .destroy = NULL, .children_changed = NULL, .connected = NULL},
    /* LXB_TAG_ISINDEX */
    {.inserted = NULL, .removed = NULL, .moved = NULL, .destroy = NULL, .children_changed = NULL, .connected = NULL},
    /* LXB_TAG_KBD */
    {.inserted = NULL, .removed = NULL, .moved = NULL, .destroy = NULL, .children_changed = NULL, .connected = NULL},
    /* LXB_TAG_KEYGEN */
    {.inserted = NULL, .removed = NULL, .moved = NULL, .destroy = NULL, .children_changed = NULL, .connected = NULL},
    /* LXB_TAG_LABEL */
    {.inserted = NULL, .removed = NULL, .moved = NULL, .destroy = NULL, .children_changed = NULL, .connected = NULL},
    /* LXB_TAG_LEGEND */
    {.inserted = NULL, .removed = NULL, .moved = NULL, .destroy = NULL, .children_changed = NULL, .connected = NULL},
    /* LXB_TAG_LI */
    {.inserted = NULL, .removed = NULL, .moved = NULL, .destroy = NULL, .children_changed = NULL, .connected = NULL},
    /* LXB_TAG_LINEARGRADIENT */
    {.inserted = NULL, .removed = NULL, .moved = NULL, .destroy = NULL, .children_changed = NULL, .connected = NULL},
    /* LXB_TAG_LINK */
    {.inserted = NULL, .removed = NULL, .moved = NULL, .destroy = NULL, .children_changed = NULL, .connected = NULL},
    /* LXB_TAG_LISTING */
    {.inserted = NULL, .removed = NULL, .moved = NULL, .destroy = NULL, .children_changed = NULL, .connected = NULL},
    /* LXB_TAG_MAIN */
    {.inserted = NULL, .removed = NULL, .moved = NULL, .destroy = NULL, .children_changed = NULL, .connected = NULL},
    /* LXB_TAG_MALIGNMARK */
    {.inserted = NULL, .removed = NULL, .moved = NULL, .destroy = NULL, .children_changed = NULL, .connected = NULL},
    /* LXB_TAG_MAP */
    {.inserted = NULL, .removed = NULL, .moved = NULL, .destroy = NULL, .children_changed = NULL, .connected = NULL},
    /* LXB_TAG_MARK */
    {.inserted = NULL, .removed = NULL, .moved = NULL, .destroy = NULL, .children_changed = NULL, .connected = NULL},
    /* LXB_TAG_MARQUEE */
    {.inserted = NULL, .removed = NULL, .moved = NULL, .destroy = NULL, .children_changed = NULL, .connected = NULL},
    /* LXB_TAG_MATH */
    {.inserted = NULL, .removed = NULL, .moved = NULL, .destroy = NULL, .children_changed = NULL, .connected = NULL},
    /* LXB_TAG_MENU */
    {.inserted = NULL, .removed = NULL, .moved = NULL, .destroy = NULL, .children_changed = NULL, .connected = NULL},
    /* LXB_TAG_META */
    {.inserted = NULL, .removed = NULL, .moved = NULL, .destroy = NULL, .children_changed = NULL, .connected = NULL},
    /* LXB_TAG_METER */
    {.inserted = NULL, .removed = NULL, .moved = NULL, .destroy = NULL, .children_changed = NULL, .connected = NULL},
    /* LXB_TAG_MFENCED */
    {.inserted = NULL, .removed = NULL, .moved = NULL, .destroy = NULL, .children_changed = NULL, .connected = NULL},
    /* LXB_TAG_MGLYPH */
    {.inserted = NULL, .removed = NULL, .moved = NULL, .destroy = NULL, .children_changed = NULL, .connected = NULL},
    /* LXB_TAG_MI */
    {.inserted = NULL, .removed = NULL, .moved = NULL, .destroy = NULL, .children_changed = NULL, .connected = NULL},
    /* LXB_TAG_MN */
    {.inserted = NULL, .removed = NULL, .moved = NULL, .destroy = NULL, .children_changed = NULL, .connected = NULL},
    /* LXB_TAG_MO */
    {.inserted = NULL, .removed = NULL, .moved = NULL, .destroy = NULL, .children_changed = NULL, .connected = NULL},
    /* LXB_TAG_MS */
    {.inserted = NULL, .removed = NULL, .moved = NULL, .destroy = NULL, .children_changed = NULL, .connected = NULL},
    /* LXB_TAG_MTEXT */
    {.inserted = NULL, .removed = NULL, .moved = NULL, .destroy = NULL, .children_changed = NULL, .connected = NULL},
    /* LXB_TAG_MULTICOL */
    {.inserted = NULL, .removed = NULL, .moved = NULL, .destroy = NULL, .children_changed = NULL, .connected = NULL},
    /* LXB_TAG_NAV */
    {.inserted = NULL, .removed = NULL, .moved = NULL, .destroy = NULL, .children_changed = NULL, .connected = NULL},
    /* LXB_TAG_NEXTID */
    {.inserted = NULL, .removed = NULL, .moved = NULL, .destroy = NULL, .children_changed = NULL, .connected = NULL},
    /* LXB_TAG_NOBR */
    {.inserted = NULL, .removed = NULL, .moved = NULL, .destroy = NULL, .children_changed = NULL, .connected = NULL},
    /* LXB_TAG_NOEMBED */
    {.inserted = NULL, .removed = NULL, .moved = NULL, .destroy = NULL, .children_changed = NULL, .connected = NULL},
    /* LXB_TAG_NOFRAMES */
    {.inserted = NULL, .removed = NULL, .moved = NULL, .destroy = NULL, .children_changed = NULL, .connected = NULL},
    /* LXB_TAG_NOSCRIPT */
    {.inserted = NULL, .removed = NULL, .moved = NULL, .destroy = NULL, .children_changed = NULL, .connected = NULL},
    /* LXB_TAG_OBJECT */
    {.inserted = NULL, .removed = NULL, .moved = NULL, .destroy = NULL, .children_changed = NULL, .connected = NULL},
    /* LXB_TAG_OL */
    {.inserted = NULL, .removed = NULL, .moved = NULL, .destroy = NULL, .children_changed = NULL, .connected = NULL},
    /* LXB_TAG_OPTGROUP */
    {.inserted = NULL, .removed = NULL, .moved = NULL, .destroy = NULL, .children_changed = NULL, .connected = NULL},
    /* LXB_TAG_OPTION */
    {.inserted = lxb_html_option_element_insert_steps, .removed = lxb_html_option_element_remove_steps, .moved = NULL, .destroy = NULL, .children_changed = NULL, .connected = NULL},
    /* LXB_TAG_OUTPUT */
    {.inserted = NULL, .removed = NULL, .moved = NULL, .destroy = NULL, .children_changed = NULL, .connected = NULL},
    /* LXB_TAG_P */
    {.inserted = NULL, .removed = NULL, .moved = NULL, .destroy = NULL, .children_changed = NULL, .connected = NULL},
    /* LXB_TAG_PARAM */
    {.inserted = NULL, .removed = NULL, .moved = NULL, .destroy = NULL, .children_changed = NULL, .connected = NULL},
    /* LXB_TAG_PATH */
    {.inserted = NULL, .removed = NULL, .moved = NULL, .destroy = NULL, .children_changed = NULL, .connected = NULL},
    /* LXB_TAG_PICTURE */
    {.inserted = NULL, .removed = NULL, .moved = NULL, .destroy = NULL, .children_changed = NULL, .connected = NULL},
    /* LXB_TAG_PLAINTEXT */
    {.inserted = NULL, .removed = NULL, .moved = NULL, .destroy = NULL, .children_changed = NULL, .connected = NULL},
    /* LXB_TAG_PRE */
    {.inserted = NULL, .removed = NULL, .moved = NULL, .destroy = NULL, .children_changed = NULL, .connected = NULL},
    /* LXB_TAG_PROGRESS */
    {.inserted = NULL, .removed = NULL, .moved = NULL, .destroy = NULL, .children_changed = NULL, .connected = NULL},
    /* LXB_TAG_Q */
    {.inserted = NULL, .removed = NULL, .moved = NULL, .destroy = NULL, .children_changed = NULL, .connected = NULL},
    /* LXB_TAG_RADIALGRADIENT */
    {.inserted = NULL, .removed = NULL, .moved = NULL, .destroy = NULL, .children_changed = NULL, .connected = NULL},
    /* LXB_TAG_RB */
    {.inserted = NULL, .removed = NULL, .moved = NULL, .destroy = NULL, .children_changed = NULL, .connected = NULL},
    /* LXB_TAG_RP */
    {.inserted = NULL, .removed = NULL, .moved = NULL, .destroy = NULL, .children_changed = NULL, .connected = NULL},
    /* LXB_TAG_RT */
    {.inserted = NULL, .removed = NULL, .moved = NULL, .destroy = NULL, .children_changed = NULL, .connected = NULL},
    /* LXB_TAG_RTC */
    {.inserted = NULL, .removed = NULL, .moved = NULL, .destroy = NULL, .children_changed = NULL, .connected = NULL},
    /* LXB_TAG_RUBY */
    {.inserted = NULL, .removed = NULL, .moved = NULL, .destroy = NULL, .children_changed = NULL, .connected = NULL},
    /* LXB_TAG_S */
    {.inserted = NULL, .removed = NULL, .moved = NULL, .destroy = NULL, .children_changed = NULL, .connected = NULL},
    /* LXB_TAG_SAMP */
    {.inserted = NULL, .removed = NULL, .moved = NULL, .destroy = NULL, .children_changed = NULL, .connected = NULL},
    /* LXB_TAG_SCRIPT */
    {.inserted = NULL, .removed = NULL, .moved = NULL, .destroy = NULL, .children_changed = NULL, .connected = NULL},
    /* LXB_TAG_SEARCH */
    {.inserted = NULL, .removed = NULL, .moved = NULL, .destroy = NULL, .children_changed = NULL, .connected = NULL},
    /* LXB_TAG_SECTION */
    {.inserted = NULL, .removed = NULL, .moved = NULL, .destroy = NULL, .children_changed = NULL, .connected = NULL},
    /* LXB_TAG_SELECT */
    {.inserted = NULL, .removed = NULL, .moved = NULL, .destroy = NULL, .children_changed = NULL, .connected = NULL},
    /* LXB_TAG_SELECTEDCONTENT */
    {.inserted = NULL, .removed = NULL, .moved = NULL, .destroy = NULL, .children_changed = NULL, .connected = NULL},
    /* LXB_TAG_SLOT */
    {.inserted = NULL, .removed = NULL, .moved = NULL, .destroy = NULL, .children_changed = NULL, .connected = NULL},
    /* LXB_TAG_SMALL */
    {.inserted = NULL, .removed = NULL, .moved = NULL, .destroy = NULL, .children_changed = NULL, .connected = NULL},
    /* LXB_TAG_SOURCE */
    {.inserted = NULL, .removed = NULL, .moved = NULL, .destroy = NULL, .children_changed = NULL, .connected = NULL},
    /* LXB_TAG_SPACER */
    {.inserted = NULL, .removed = NULL, .moved = NULL, .destroy = NULL, .children_changed = NULL, .connected = NULL},
    /* LXB_TAG_SPAN */
    {.inserted = NULL, .removed = NULL, .moved = NULL, .destroy = NULL, .children_changed = NULL, .connected = NULL},
    /* LXB_TAG_STRIKE */
    {.inserted = NULL, .removed = NULL, .moved = NULL, .destroy = NULL, .children_changed = NULL, .connected = NULL},
    /* LXB_TAG_STRONG */
    {.inserted = NULL, .removed = NULL, .moved = NULL, .destroy = NULL, .children_changed = NULL, .connected = NULL},
    /* LXB_TAG_STYLE */
    {.inserted = NULL, .removed = NULL, .moved = NULL, .destroy = NULL, .children_changed = NULL, .connected = NULL},
    /* LXB_TAG_SUB */
    {.inserted = NULL, .removed = NULL, .moved = NULL, .destroy = NULL, .children_changed = NULL, .connected = NULL},
    /* LXB_TAG_SUMMARY */
    {.inserted = NULL, .removed = NULL, .moved = NULL, .destroy = NULL, .children_changed = NULL, .connected = NULL},
    /* LXB_TAG_SUP */
    {.inserted = NULL, .removed = NULL, .moved = NULL, .destroy = NULL, .children_changed = NULL, .connected = NULL},
    /* LXB_TAG_SVG */
    {.inserted = NULL, .removed = NULL, .moved = NULL, .destroy = NULL, .children_changed = NULL, .connected = NULL},
    /* LXB_TAG_TABLE */
    {.inserted = NULL, .removed = NULL, .moved = NULL, .destroy = NULL, .children_changed = NULL, .connected = NULL},
    /* LXB_TAG_TBODY */
    {.inserted = NULL, .removed = NULL, .moved = NULL, .destroy = NULL, .children_changed = NULL, .connected = NULL},
    /* LXB_TAG_TD */
    {.inserted = NULL, .removed = NULL, .moved = NULL, .destroy = NULL, .children_changed = NULL, .connected = NULL},
    /* LXB_TAG_TEMPLATE */
    {.inserted = NULL, .removed = NULL, .moved = NULL, .destroy = NULL, .children_changed = NULL, .connected = NULL},
    /* LXB_TAG_TEXTAREA */
    {.inserted = NULL, .removed = NULL, .moved = NULL, .destroy = NULL, .children_changed = NULL, .connected = NULL},
    /* LXB_TAG_TEXTPATH */
    {.inserted = NULL, .removed = NULL, .moved = NULL, .destroy = NULL, .children_changed = NULL, .connected = NULL},
    /* LXB_TAG_TFOOT */
    {.inserted = NULL, .removed = NULL, .moved = NULL, .destroy = NULL, .children_changed = NULL, .connected = NULL},
    /* LXB_TAG_TH */
    {.inserted = NULL, .removed = NULL, .moved = NULL, .destroy = NULL, .children_changed = NULL, .connected = NULL},
    /* LXB_TAG_THEAD */
    {.inserted = NULL, .removed = NULL, .moved = NULL, .destroy = NULL, .children_changed = NULL, .connected = NULL},
    /* LXB_TAG_TIME */
    {.inserted = NULL, .removed = NULL, .moved = NULL, .destroy = NULL, .children_changed = NULL, .connected = NULL},
    /* LXB_TAG_TITLE */
    {.inserted = NULL, .removed = NULL, .moved = NULL, .destroy = NULL, .children_changed = NULL, .connected = NULL},
    /* LXB_TAG_TR */
    {.inserted = NULL, .removed = NULL, .moved = NULL, .destroy = NULL, .children_changed = NULL, .connected = NULL},
    /* LXB_TAG_TRACK */
    {.inserted = NULL, .removed = NULL, .moved = NULL, .destroy = NULL, .children_changed = NULL, .connected = NULL},
    /* LXB_TAG_TT */
    {.inserted = NULL, .removed = NULL, .moved = NULL, .destroy = NULL, .children_changed = NULL, .connected = NULL},
    /* LXB_TAG_U */
    {.inserted = NULL, .removed = NULL, .moved = NULL, .destroy = NULL, .children_changed = NULL, .connected = NULL},
    /* LXB_TAG_UL */
    {.inserted = NULL, .removed = NULL, .moved = NULL, .destroy = NULL, .children_changed = NULL, .connected = NULL},
    /* LXB_TAG_VAR */
    {.inserted = NULL, .removed = NULL, .moved = NULL, .destroy = NULL, .children_changed = NULL, .connected = NULL},
    /* LXB_TAG_VIDEO */
    {.inserted = NULL, .removed = NULL, .moved = NULL, .destroy = NULL, .children_changed = NULL, .connected = NULL},
    /* LXB_TAG_WBR */
    {.inserted = NULL, .removed = NULL, .moved = NULL, .destroy = NULL, .children_changed = NULL, .connected = NULL},
    /* LXB_TAG_XMP */
    {.inserted = NULL, .removed = NULL, .moved = NULL, .destroy = NULL, .children_changed = NULL, .connected = NULL}
};

#endif /* LXB_HTML_ELEMENT_STEPS_RES_H */
