/*
 * Copyright (C) 2018 Alexander Borisov
 *
 * Author: Alexander Borisov <lex.borisov@gmail.com>
 */

/*
 * Caution!!! Important!!!
 * This file generated by the script "utils/lexbor/html/tags.py"!
 * Do not change this file!
 */


#ifndef LXB_HTML_NS_CONST_H
#define LXB_HTML_NS_CONST_H

#define LXB_HTML_NS_CONST_VERSION "3A3A54D256E0D335D876F9E54A5BC239"
#define LXB_HTML_NS_CONST_VERSION_3A3A54D256E0D335D876F9E54A5BC239

typedef unsigned int lxb_html_ns_id_t;

typedef enum {
    LXB_HTML_NS__UNDEF      = 0x00,
    LXB_HTML_NS__ANY        = 0x01,
    LXB_HTML_NS_HTML        = 0x02,
    LXB_HTML_NS_MATH        = 0x03,
    LXB_HTML_NS_SVG         = 0x04,
    LXB_HTML_NS_XLINK       = 0x05,
    LXB_HTML_NS_XML         = 0x06,
    LXB_HTML_NS_XMLNS       = 0x07,
    LXB_HTML_NS__LAST_ENTRY = 0x08
}
lxb_html_ns_id_enum_t;


#endif /* LXB_HTML_NS_CONST_H */
