/*
 * Copyright (C) 2018 Alexander Borisov
 *
 * Author: Alexander Borisov <lex.borisov@gmail.com>
 */

/*
 * Caution!!! Important!!!
 * This file generated by the script "utils/lexbor/html/tags.py"!
 * Do not change this file!
 */


#ifndef LXB_HTML_NS_RES_H
#define LXB_HTML_NS_RES_H

#endif /* LXB_HTML_NS_RES_H */


#ifdef LXB_HTML_NS_CONST_VERSION
#ifndef LXB_HTML_NS_CONST_VERSION_392192FF2346B29C1732921F421BEB79
#error Mismatched namespaces version! See "lexbor/html/ns_const.h".
#endif /* LXB_HTML_NS_CONST_VERSION_392192FF2346B29C1732921F421BEB79 */
#else
#error You need to include "lexbor/html/ns_const.h".
#endif /* LXB_HTML_NS_CONST_VERSION */

#ifdef LXB_HTML_NS_RES_DATA
#ifndef LXB_HTML_NS_RES_DATA_ENABLED
#define LXB_HTML_NS_RES_DATA_ENABLED
static  lxb_html_ns_data_t lxb_html_ns_res_data[LXB_HTML_NS__LAST_ENTRY] = 
{
    {"-undef", 6, "", 0, LXB_HTML_NS__UNDEF},
    {"-any", 4, "", 0, LXB_HTML_NS__ANY},
    {"HTML", 4, "http://www.w3.org/1999/xhtml", 28, LXB_HTML_NS_HTML},
    {"MathML", 6, "http://www.w3.org/1998/Math/MathML", 34, LXB_HTML_NS_MATHML},
    {"SVG", 3, "http://www.w3.org/2000/svg", 26, LXB_HTML_NS_SVG},
    {"XLink", 5, "http://www.w3.org/1999/xlink", 28, LXB_HTML_NS_XLINK},
    {"XML", 3, "http://www.w3.org/XML/1998/namespace", 36, LXB_HTML_NS_XML},
    {"XMLNS", 5, "http://www.w3.org/2000/xmlns/", 29, LXB_HTML_NS_XMLNS}
};
#endif /* LXB_HTML_NS_RES_DATA_ENABLED */
#endif /* LXB_HTML_NS_RES_DATA */

#ifdef LXB_HTML_NS_RES_SHS_DATA
#ifndef LXB_HTML_NS_RES_SHS_DATA_ENABLED
#define LXB_HTML_NS_RES_SHS_DATA_ENABLED
static const lexbor_shs_entry_t lxb_html_ns_res_shs_data[] = 
{
    {NULL, NULL, 19, 0}, {"XLINK", &lxb_html_ns_res_data[5], 5, 0}, 
    {NULL, NULL, 0, 0}, {NULL, NULL, 0, 0}, 
    {"XMLNS", &lxb_html_ns_res_data[7], 5, 0}, {NULL, NULL, 0, 0}, 
    {"-ANY", &lxb_html_ns_res_data[1], 4, 0}, {NULL, NULL, 0, 0}, 
    {"-UNDEF", &lxb_html_ns_res_data[0], 6, 0}, {"MATHML", &lxb_html_ns_res_data[3], 6, 0}, 
    {NULL, NULL, 0, 0}, {NULL, NULL, 0, 0}, 
    {"SVG", &lxb_html_ns_res_data[4], 3, 0}, {"HTML", &lxb_html_ns_res_data[2], 4, 0}, 
    {NULL, NULL, 0, 0}, {NULL, NULL, 0, 0}, 
    {"XML", &lxb_html_ns_res_data[6], 3, 0}, {NULL, NULL, 0, 0}, 
    {NULL, NULL, 0, 0}, {NULL, NULL, 0, 0}
};
#endif /* LXB_HTML_NS_RES_SHS_DATA_ENABLED */
#endif /* LXB_HTML_NS_RES_SHS_DATA */
