/*
 * Copyright (C) 2018 Alexander Borisov
 *
 * Author: Alexander Borisov <lex.borisov@gmail.com>
 */

#ifndef LXB_HTML_TREE_INSERTION_MODE_IN_ROW_H
#define LXB_HTML_TREE_INSERTION_MODE_IN_ROW_H

#ifdef LXB_TAG_CONST_VERSION
#ifndef LXB_TAG_CONST_VERSION_A161EC911182C3254E7A972D5C51DF86
#error Mismatched tags version! See "lexbor/tag/const.h".
#endif /* LXB_TAG_CONST_VERSION_A161EC911182C3254E7A972D5C51DF86 */
#else
#error You need to include "lexbor/tag/const.h".
#endif /* LXB_TAG_CONST_VERSION */


static const lxb_html_tree_insertion_mode_f
lxb_html_tree_insertion_mode_in_row_res[] = 
{
    lxb_html_tree_insertion_mode_in_row_anything_else, /* LXB_TAG__UNDEF */
    lxb_html_tree_insertion_mode_in_row_anything_else, /* LXB_TAG__END_OF_FILE */
    lxb_html_tree_insertion_mode_in_row_anything_else, /* LXB_TAG__TEXT */
    lxb_html_tree_insertion_mode_in_row_anything_else, /* LXB_TAG__DOCUMENT */
    lxb_html_tree_insertion_mode_in_row_anything_else, /* LXB_TAG__EM_COMMENT */
    lxb_html_tree_insertion_mode_in_row_anything_else, /* LXB_TAG__EM_DOCTYPE */
    lxb_html_tree_insertion_mode_in_row_anything_else, /* LXB_TAG_A */
    lxb_html_tree_insertion_mode_in_row_anything_else, /* LXB_TAG_ABBR */
    lxb_html_tree_insertion_mode_in_row_anything_else, /* LXB_TAG_ACRONYM */
    lxb_html_tree_insertion_mode_in_row_anything_else, /* LXB_TAG_ADDRESS */
    lxb_html_tree_insertion_mode_in_row_anything_else /* LXB_TAG_ALTGLYPH */,
    lxb_html_tree_insertion_mode_in_row_anything_else /* LXB_TAG_ALTGLYPHDEF */,
    lxb_html_tree_insertion_mode_in_row_anything_else /* LXB_TAG_ALTGLYPHITEM */,
    lxb_html_tree_insertion_mode_in_row_anything_else /* LXB_TAG_ANIMATECOLOR */,
    lxb_html_tree_insertion_mode_in_row_anything_else /* LXB_TAG_ANIMATEMOTION */,
    lxb_html_tree_insertion_mode_in_row_anything_else /* LXB_TAG_ANIMATETRANSFORM */,
    lxb_html_tree_insertion_mode_in_row_anything_else, /* LXB_TAG_ANNOTATION_XML */
    lxb_html_tree_insertion_mode_in_row_anything_else, /* LXB_TAG_APPLET */
    lxb_html_tree_insertion_mode_in_row_anything_else, /* LXB_TAG_AREA */
    lxb_html_tree_insertion_mode_in_row_anything_else, /* LXB_TAG_ARTICLE */
    lxb_html_tree_insertion_mode_in_row_anything_else, /* LXB_TAG_ASIDE */
    lxb_html_tree_insertion_mode_in_row_anything_else, /* LXB_TAG_AUDIO */
    lxb_html_tree_insertion_mode_in_row_anything_else, /* LXB_TAG_B */
    lxb_html_tree_insertion_mode_in_row_anything_else, /* LXB_TAG_BASE */
    lxb_html_tree_insertion_mode_in_row_anything_else, /* LXB_TAG_BASEFONT */
    lxb_html_tree_insertion_mode_in_row_anything_else, /* LXB_TAG_BDI */
    lxb_html_tree_insertion_mode_in_row_anything_else, /* LXB_TAG_BDO */
    lxb_html_tree_insertion_mode_in_row_anything_else, /* LXB_TAG_BGSOUND */
    lxb_html_tree_insertion_mode_in_row_anything_else, /* LXB_TAG_BIG */
    lxb_html_tree_insertion_mode_in_row_anything_else, /* LXB_TAG_BLINK */
    lxb_html_tree_insertion_mode_in_row_anything_else, /* LXB_TAG_BLOCKQUOTE */
    lxb_html_tree_insertion_mode_in_row_anything_else, /* LXB_TAG_BODY */
    lxb_html_tree_insertion_mode_in_row_anything_else, /* LXB_TAG_BR */
    lxb_html_tree_insertion_mode_in_row_anything_else, /* LXB_TAG_BUTTON */
    lxb_html_tree_insertion_mode_in_row_anything_else, /* LXB_TAG_CANVAS */
    lxb_html_tree_insertion_mode_in_row_ct_open_closed, /* LXB_TAG_CAPTION */
    lxb_html_tree_insertion_mode_in_row_anything_else, /* LXB_TAG_CENTER */
    lxb_html_tree_insertion_mode_in_row_anything_else, /* LXB_TAG_CITE */
    lxb_html_tree_insertion_mode_in_row_anything_else /* LXB_TAG_CLIPPATH */,
    lxb_html_tree_insertion_mode_in_row_anything_else, /* LXB_TAG_CODE */
    lxb_html_tree_insertion_mode_in_row_ct_open_closed, /* LXB_TAG_COL */
    lxb_html_tree_insertion_mode_in_row_ct_open_closed, /* LXB_TAG_COLGROUP */
    lxb_html_tree_insertion_mode_in_row_anything_else, /* LXB_TAG_DATA */
    lxb_html_tree_insertion_mode_in_row_anything_else, /* LXB_TAG_DATALIST */
    lxb_html_tree_insertion_mode_in_row_anything_else, /* LXB_TAG_DD */
    lxb_html_tree_insertion_mode_in_row_anything_else, /* LXB_TAG_DEL */
    lxb_html_tree_insertion_mode_in_row_anything_else, /* LXB_TAG_DESC */
    lxb_html_tree_insertion_mode_in_row_anything_else, /* LXB_TAG_DETAILS */
    lxb_html_tree_insertion_mode_in_row_anything_else, /* LXB_TAG_DFN */
    lxb_html_tree_insertion_mode_in_row_anything_else, /* LXB_TAG_DIALOG */
    lxb_html_tree_insertion_mode_in_row_anything_else, /* LXB_TAG_DIR */
    lxb_html_tree_insertion_mode_in_row_anything_else, /* LXB_TAG_DIV */
    lxb_html_tree_insertion_mode_in_row_anything_else, /* LXB_TAG_DL */
    lxb_html_tree_insertion_mode_in_row_anything_else, /* LXB_TAG_DT */
    lxb_html_tree_insertion_mode_in_row_anything_else, /* LXB_TAG_EM */
    lxb_html_tree_insertion_mode_in_row_anything_else, /* LXB_TAG_EMBED */
    lxb_html_tree_insertion_mode_in_row_anything_else /* LXB_TAG_FEBLEND */,
    lxb_html_tree_insertion_mode_in_row_anything_else /* LXB_TAG_FECOLORMATRIX */,
    lxb_html_tree_insertion_mode_in_row_anything_else /* LXB_TAG_FECOMPONENTTRANSFER */,
    lxb_html_tree_insertion_mode_in_row_anything_else /* LXB_TAG_FECOMPOSITE */,
    lxb_html_tree_insertion_mode_in_row_anything_else /* LXB_TAG_FECONVOLVEMATRIX */,
    lxb_html_tree_insertion_mode_in_row_anything_else /* LXB_TAG_FEDIFFUSELIGHTING */,
    lxb_html_tree_insertion_mode_in_row_anything_else /* LXB_TAG_FEDISPLACEMENTMAP */,
    lxb_html_tree_insertion_mode_in_row_anything_else /* LXB_TAG_FEDISTANTLIGHT */,
    lxb_html_tree_insertion_mode_in_row_anything_else /* LXB_TAG_FEDROPSHADOW */,
    lxb_html_tree_insertion_mode_in_row_anything_else /* LXB_TAG_FEFLOOD */,
    lxb_html_tree_insertion_mode_in_row_anything_else /* LXB_TAG_FEFUNCA */,
    lxb_html_tree_insertion_mode_in_row_anything_else /* LXB_TAG_FEFUNCB */,
    lxb_html_tree_insertion_mode_in_row_anything_else /* LXB_TAG_FEFUNCG */,
    lxb_html_tree_insertion_mode_in_row_anything_else /* LXB_TAG_FEFUNCR */,
    lxb_html_tree_insertion_mode_in_row_anything_else /* LXB_TAG_FEGAUSSIANBLUR */,
    lxb_html_tree_insertion_mode_in_row_anything_else /* LXB_TAG_FEIMAGE */,
    lxb_html_tree_insertion_mode_in_row_anything_else /* LXB_TAG_FEMERGE */,
    lxb_html_tree_insertion_mode_in_row_anything_else /* LXB_TAG_FEMERGENODE */,
    lxb_html_tree_insertion_mode_in_row_anything_else /* LXB_TAG_FEMORPHOLOGY */,
    lxb_html_tree_insertion_mode_in_row_anything_else /* LXB_TAG_FEOFFSET */,
    lxb_html_tree_insertion_mode_in_row_anything_else /* LXB_TAG_FEPOINTLIGHT */,
    lxb_html_tree_insertion_mode_in_row_anything_else /* LXB_TAG_FESPECULARLIGHTING */,
    lxb_html_tree_insertion_mode_in_row_anything_else /* LXB_TAG_FESPOTLIGHT */,
    lxb_html_tree_insertion_mode_in_row_anything_else /* LXB_TAG_FETILE */,
    lxb_html_tree_insertion_mode_in_row_anything_else /* LXB_TAG_FETURBULENCE */,
    lxb_html_tree_insertion_mode_in_row_anything_else, /* LXB_TAG_FIELDSET */
    lxb_html_tree_insertion_mode_in_row_anything_else, /* LXB_TAG_FIGCAPTION */
    lxb_html_tree_insertion_mode_in_row_anything_else, /* LXB_TAG_FIGURE */
    lxb_html_tree_insertion_mode_in_row_anything_else, /* LXB_TAG_FONT */
    lxb_html_tree_insertion_mode_in_row_anything_else, /* LXB_TAG_FOOTER */
    lxb_html_tree_insertion_mode_in_row_anything_else, /* LXB_TAG_FOREIGNOBJECT */
    lxb_html_tree_insertion_mode_in_row_anything_else, /* LXB_TAG_FORM */
    lxb_html_tree_insertion_mode_in_row_anything_else, /* LXB_TAG_FRAME */
    lxb_html_tree_insertion_mode_in_row_anything_else, /* LXB_TAG_FRAMESET */
    lxb_html_tree_insertion_mode_in_row_anything_else /* LXB_TAG_GLYPHREF */,
    lxb_html_tree_insertion_mode_in_row_anything_else, /* LXB_TAG_H1 */
    lxb_html_tree_insertion_mode_in_row_anything_else, /* LXB_TAG_H2 */
    lxb_html_tree_insertion_mode_in_row_anything_else, /* LXB_TAG_H3 */
    lxb_html_tree_insertion_mode_in_row_anything_else, /* LXB_TAG_H4 */
    lxb_html_tree_insertion_mode_in_row_anything_else, /* LXB_TAG_H5 */
    lxb_html_tree_insertion_mode_in_row_anything_else, /* LXB_TAG_H6 */
    lxb_html_tree_insertion_mode_in_row_anything_else, /* LXB_TAG_HEAD */
    lxb_html_tree_insertion_mode_in_row_anything_else, /* LXB_TAG_HEADER */
    lxb_html_tree_insertion_mode_in_row_anything_else, /* LXB_TAG_HGROUP */
    lxb_html_tree_insertion_mode_in_row_anything_else, /* LXB_TAG_HR */
    lxb_html_tree_insertion_mode_in_row_anything_else, /* LXB_TAG_HTML */
    lxb_html_tree_insertion_mode_in_row_anything_else, /* LXB_TAG_I */
    lxb_html_tree_insertion_mode_in_row_anything_else, /* LXB_TAG_IFRAME */
    lxb_html_tree_insertion_mode_in_row_anything_else, /* LXB_TAG_IMAGE */
    lxb_html_tree_insertion_mode_in_row_anything_else, /* LXB_TAG_IMG */
    lxb_html_tree_insertion_mode_in_row_anything_else, /* LXB_TAG_INPUT */
    lxb_html_tree_insertion_mode_in_row_anything_else, /* LXB_TAG_INS */
    lxb_html_tree_insertion_mode_in_row_anything_else, /* LXB_TAG_ISINDEX */
    lxb_html_tree_insertion_mode_in_row_anything_else, /* LXB_TAG_KBD */
    lxb_html_tree_insertion_mode_in_row_anything_else, /* LXB_TAG_KEYGEN */
    lxb_html_tree_insertion_mode_in_row_anything_else, /* LXB_TAG_LABEL */
    lxb_html_tree_insertion_mode_in_row_anything_else, /* LXB_TAG_LEGEND */
    lxb_html_tree_insertion_mode_in_row_anything_else, /* LXB_TAG_LI */
    lxb_html_tree_insertion_mode_in_row_anything_else /* LXB_TAG_LINEARGRADIENT */,
    lxb_html_tree_insertion_mode_in_row_anything_else, /* LXB_TAG_LINK */
    lxb_html_tree_insertion_mode_in_row_anything_else, /* LXB_TAG_LISTING */
    lxb_html_tree_insertion_mode_in_row_anything_else, /* LXB_TAG_MAIN */
    lxb_html_tree_insertion_mode_in_row_anything_else, /* LXB_TAG_MALIGNMARK */
    lxb_html_tree_insertion_mode_in_row_anything_else, /* LXB_TAG_MAP */
    lxb_html_tree_insertion_mode_in_row_anything_else, /* LXB_TAG_MARK */
    lxb_html_tree_insertion_mode_in_row_anything_else, /* LXB_TAG_MARQUEE */
    lxb_html_tree_insertion_mode_in_row_anything_else, /* LXB_TAG_MATH */
    lxb_html_tree_insertion_mode_in_row_anything_else, /* LXB_TAG_MENU */
    lxb_html_tree_insertion_mode_in_row_anything_else, /* LXB_TAG_META */
    lxb_html_tree_insertion_mode_in_row_anything_else, /* LXB_TAG_METER */
    lxb_html_tree_insertion_mode_in_row_anything_else, /* LXB_TAG_MFENCED */
    lxb_html_tree_insertion_mode_in_row_anything_else, /* LXB_TAG_MGLYPH */
    lxb_html_tree_insertion_mode_in_row_anything_else, /* LXB_TAG_MI */
    lxb_html_tree_insertion_mode_in_row_anything_else, /* LXB_TAG_MN */
    lxb_html_tree_insertion_mode_in_row_anything_else, /* LXB_TAG_MO */
    lxb_html_tree_insertion_mode_in_row_anything_else, /* LXB_TAG_MS */
    lxb_html_tree_insertion_mode_in_row_anything_else, /* LXB_TAG_MTEXT */
    lxb_html_tree_insertion_mode_in_row_anything_else, /* LXB_TAG_MULTICOL */
    lxb_html_tree_insertion_mode_in_row_anything_else, /* LXB_TAG_NAV */
    lxb_html_tree_insertion_mode_in_row_anything_else, /* LXB_TAG_NEXTID */
    lxb_html_tree_insertion_mode_in_row_anything_else, /* LXB_TAG_NOBR */
    lxb_html_tree_insertion_mode_in_row_anything_else, /* LXB_TAG_NOEMBED */
    lxb_html_tree_insertion_mode_in_row_anything_else, /* LXB_TAG_NOFRAMES */
    lxb_html_tree_insertion_mode_in_row_anything_else, /* LXB_TAG_NOSCRIPT */
    lxb_html_tree_insertion_mode_in_row_anything_else, /* LXB_TAG_OBJECT */
    lxb_html_tree_insertion_mode_in_row_anything_else, /* LXB_TAG_OL */
    lxb_html_tree_insertion_mode_in_row_anything_else, /* LXB_TAG_OPTGROUP */
    lxb_html_tree_insertion_mode_in_row_anything_else, /* LXB_TAG_OPTION */
    lxb_html_tree_insertion_mode_in_row_anything_else, /* LXB_TAG_OUTPUT */
    lxb_html_tree_insertion_mode_in_row_anything_else, /* LXB_TAG_P */
    lxb_html_tree_insertion_mode_in_row_anything_else, /* LXB_TAG_PARAM */
    lxb_html_tree_insertion_mode_in_row_anything_else, /* LXB_TAG_PATH */
    lxb_html_tree_insertion_mode_in_row_anything_else, /* LXB_TAG_PICTURE */
    lxb_html_tree_insertion_mode_in_row_anything_else, /* LXB_TAG_PLAINTEXT */
    lxb_html_tree_insertion_mode_in_row_anything_else, /* LXB_TAG_PRE */
    lxb_html_tree_insertion_mode_in_row_anything_else, /* LXB_TAG_PROGRESS */
    lxb_html_tree_insertion_mode_in_row_anything_else, /* LXB_TAG_Q */
    lxb_html_tree_insertion_mode_in_row_anything_else /* LXB_TAG_RADIALGRADIENT */,
    lxb_html_tree_insertion_mode_in_row_anything_else, /* LXB_TAG_RB */
    lxb_html_tree_insertion_mode_in_row_anything_else, /* LXB_TAG_RP */
    lxb_html_tree_insertion_mode_in_row_anything_else, /* LXB_TAG_RT */
    lxb_html_tree_insertion_mode_in_row_anything_else, /* LXB_TAG_RTC */
    lxb_html_tree_insertion_mode_in_row_anything_else, /* LXB_TAG_RUBY */
    lxb_html_tree_insertion_mode_in_row_anything_else, /* LXB_TAG_S */
    lxb_html_tree_insertion_mode_in_row_anything_else, /* LXB_TAG_SAMP */
    lxb_html_tree_insertion_mode_in_row_anything_else, /* LXB_TAG_SCRIPT */
    lxb_html_tree_insertion_mode_in_row_anything_else, /* LXB_TAG_SECTION */
    lxb_html_tree_insertion_mode_in_row_anything_else, /* LXB_TAG_SELECT */
    lxb_html_tree_insertion_mode_in_row_anything_else, /* LXB_TAG_SLOT */
    lxb_html_tree_insertion_mode_in_row_anything_else, /* LXB_TAG_SMALL */
    lxb_html_tree_insertion_mode_in_row_anything_else, /* LXB_TAG_SOURCE */
    lxb_html_tree_insertion_mode_in_row_anything_else, /* LXB_TAG_SPACER */
    lxb_html_tree_insertion_mode_in_row_anything_else, /* LXB_TAG_SPAN */
    lxb_html_tree_insertion_mode_in_row_anything_else, /* LXB_TAG_STRIKE */
    lxb_html_tree_insertion_mode_in_row_anything_else, /* LXB_TAG_STRONG */
    lxb_html_tree_insertion_mode_in_row_anything_else, /* LXB_TAG_STYLE */
    lxb_html_tree_insertion_mode_in_row_anything_else, /* LXB_TAG_SUB */
    lxb_html_tree_insertion_mode_in_row_anything_else, /* LXB_TAG_SUMMARY */
    lxb_html_tree_insertion_mode_in_row_anything_else, /* LXB_TAG_SUP */
    lxb_html_tree_insertion_mode_in_row_anything_else, /* LXB_TAG_SVG */
    lxb_html_tree_insertion_mode_in_row_anything_else, /* LXB_TAG_TABLE */
    lxb_html_tree_insertion_mode_in_row_ct_open_closed, /* LXB_TAG_TBODY */
    lxb_html_tree_insertion_mode_in_row_thtd, /* LXB_TAG_TD */
    lxb_html_tree_insertion_mode_in_row_anything_else, /* LXB_TAG_TEMPLATE */
    lxb_html_tree_insertion_mode_in_row_anything_else, /* LXB_TAG_TEXTAREA */
    lxb_html_tree_insertion_mode_in_row_anything_else /* LXB_TAG_TEXTPATH */,
    lxb_html_tree_insertion_mode_in_row_ct_open_closed, /* LXB_TAG_TFOOT */
    lxb_html_tree_insertion_mode_in_row_thtd, /* LXB_TAG_TH */
    lxb_html_tree_insertion_mode_in_row_ct_open_closed, /* LXB_TAG_THEAD */
    lxb_html_tree_insertion_mode_in_row_anything_else, /* LXB_TAG_TIME */
    lxb_html_tree_insertion_mode_in_row_anything_else, /* LXB_TAG_TITLE */
    lxb_html_tree_insertion_mode_in_row_ct_open_closed, /* LXB_TAG_TR */
    lxb_html_tree_insertion_mode_in_row_anything_else, /* LXB_TAG_TRACK */
    lxb_html_tree_insertion_mode_in_row_anything_else, /* LXB_TAG_TT */
    lxb_html_tree_insertion_mode_in_row_anything_else, /* LXB_TAG_U */
    lxb_html_tree_insertion_mode_in_row_anything_else, /* LXB_TAG_UL */
    lxb_html_tree_insertion_mode_in_row_anything_else, /* LXB_TAG_VAR */
    lxb_html_tree_insertion_mode_in_row_anything_else, /* LXB_TAG_VIDEO */
    lxb_html_tree_insertion_mode_in_row_anything_else, /* LXB_TAG_WBR */
    lxb_html_tree_insertion_mode_in_row_anything_else  /* LXB_TAG_XMP */
};

static const lxb_html_tree_insertion_mode_f
lxb_html_tree_insertion_mode_in_row_closed_res[] =
{
    lxb_html_tree_insertion_mode_in_row_anything_else_closed, /* LXB_TAG__UNDEF */
    lxb_html_tree_insertion_mode_in_row_anything_else_closed, /* LXB_TAG__END_OF_FILE */
    lxb_html_tree_insertion_mode_in_row_anything_else_closed, /* LXB_TAG__TEXT */
    lxb_html_tree_insertion_mode_in_row_anything_else_closed, /* LXB_TAG__DOCUMENT */
    lxb_html_tree_insertion_mode_in_row_anything_else_closed, /* LXB_TAG__EM_COMMENT */
    lxb_html_tree_insertion_mode_in_row_anything_else_closed, /* LXB_TAG__EM_DOCTYPE */
    lxb_html_tree_insertion_mode_in_row_anything_else_closed, /* LXB_TAG_A */
    lxb_html_tree_insertion_mode_in_row_anything_else_closed, /* LXB_TAG_ABBR */
    lxb_html_tree_insertion_mode_in_row_anything_else_closed, /* LXB_TAG_ACRONYM */
    lxb_html_tree_insertion_mode_in_row_anything_else_closed, /* LXB_TAG_ADDRESS */
    lxb_html_tree_insertion_mode_in_row_anything_else_closed /* LXB_TAG_ALTGLYPH */,
    lxb_html_tree_insertion_mode_in_row_anything_else_closed /* LXB_TAG_ALTGLYPHDEF */,
    lxb_html_tree_insertion_mode_in_row_anything_else_closed /* LXB_TAG_ALTGLYPHITEM */,
    lxb_html_tree_insertion_mode_in_row_anything_else_closed /* LXB_TAG_ANIMATECOLOR */,
    lxb_html_tree_insertion_mode_in_row_anything_else_closed /* LXB_TAG_ANIMATEMOTION */,
    lxb_html_tree_insertion_mode_in_row_anything_else_closed /* LXB_TAG_ANIMATETRANSFORM */,
    lxb_html_tree_insertion_mode_in_row_anything_else_closed, /* LXB_TAG_ANNOTATION_XML */
    lxb_html_tree_insertion_mode_in_row_anything_else_closed, /* LXB_TAG_APPLET */
    lxb_html_tree_insertion_mode_in_row_anything_else_closed, /* LXB_TAG_AREA */
    lxb_html_tree_insertion_mode_in_row_anything_else_closed, /* LXB_TAG_ARTICLE */
    lxb_html_tree_insertion_mode_in_row_anything_else_closed, /* LXB_TAG_ASIDE */
    lxb_html_tree_insertion_mode_in_row_anything_else_closed, /* LXB_TAG_AUDIO */
    lxb_html_tree_insertion_mode_in_row_anything_else_closed, /* LXB_TAG_B */
    lxb_html_tree_insertion_mode_in_row_anything_else_closed, /* LXB_TAG_BASE */
    lxb_html_tree_insertion_mode_in_row_anything_else_closed, /* LXB_TAG_BASEFONT */
    lxb_html_tree_insertion_mode_in_row_anything_else_closed, /* LXB_TAG_BDI */
    lxb_html_tree_insertion_mode_in_row_anything_else_closed, /* LXB_TAG_BDO */
    lxb_html_tree_insertion_mode_in_row_anything_else_closed, /* LXB_TAG_BGSOUND */
    lxb_html_tree_insertion_mode_in_row_anything_else_closed, /* LXB_TAG_BIG */
    lxb_html_tree_insertion_mode_in_row_anything_else_closed, /* LXB_TAG_BLINK */
    lxb_html_tree_insertion_mode_in_row_anything_else_closed, /* LXB_TAG_BLOCKQUOTE */
    lxb_html_tree_insertion_mode_in_row_bcht_closed, /* LXB_TAG_BODY */
    lxb_html_tree_insertion_mode_in_row_anything_else_closed, /* LXB_TAG_BR */
    lxb_html_tree_insertion_mode_in_row_anything_else_closed, /* LXB_TAG_BUTTON */
    lxb_html_tree_insertion_mode_in_row_anything_else_closed, /* LXB_TAG_CANVAS */
    lxb_html_tree_insertion_mode_in_row_bcht_closed, /* LXB_TAG_CAPTION */
    lxb_html_tree_insertion_mode_in_row_anything_else_closed, /* LXB_TAG_CENTER */
    lxb_html_tree_insertion_mode_in_row_anything_else_closed, /* LXB_TAG_CITE */
    lxb_html_tree_insertion_mode_in_row_anything_else_closed /* LXB_TAG_CLIPPATH */,
    lxb_html_tree_insertion_mode_in_row_anything_else_closed, /* LXB_TAG_CODE */
    lxb_html_tree_insertion_mode_in_row_bcht_closed, /* LXB_TAG_COL */
    lxb_html_tree_insertion_mode_in_row_bcht_closed, /* LXB_TAG_COLGROUP */
    lxb_html_tree_insertion_mode_in_row_anything_else_closed, /* LXB_TAG_DATA */
    lxb_html_tree_insertion_mode_in_row_anything_else_closed, /* LXB_TAG_DATALIST */
    lxb_html_tree_insertion_mode_in_row_anything_else_closed, /* LXB_TAG_DD */
    lxb_html_tree_insertion_mode_in_row_anything_else_closed, /* LXB_TAG_DEL */
    lxb_html_tree_insertion_mode_in_row_anything_else_closed, /* LXB_TAG_DESC */
    lxb_html_tree_insertion_mode_in_row_anything_else_closed, /* LXB_TAG_DETAILS */
    lxb_html_tree_insertion_mode_in_row_anything_else_closed, /* LXB_TAG_DFN */
    lxb_html_tree_insertion_mode_in_row_anything_else_closed, /* LXB_TAG_DIALOG */
    lxb_html_tree_insertion_mode_in_row_anything_else_closed, /* LXB_TAG_DIR */
    lxb_html_tree_insertion_mode_in_row_anything_else_closed, /* LXB_TAG_DIV */
    lxb_html_tree_insertion_mode_in_row_anything_else_closed, /* LXB_TAG_DL */
    lxb_html_tree_insertion_mode_in_row_anything_else_closed, /* LXB_TAG_DT */
    lxb_html_tree_insertion_mode_in_row_anything_else_closed, /* LXB_TAG_EM */
    lxb_html_tree_insertion_mode_in_row_anything_else_closed, /* LXB_TAG_EMBED */
    lxb_html_tree_insertion_mode_in_row_anything_else_closed /* LXB_TAG_FEBLEND */,
    lxb_html_tree_insertion_mode_in_row_anything_else_closed /* LXB_TAG_FECOLORMATRIX */,
    lxb_html_tree_insertion_mode_in_row_anything_else_closed /* LXB_TAG_FECOMPONENTTRANSFER */,
    lxb_html_tree_insertion_mode_in_row_anything_else_closed /* LXB_TAG_FECOMPOSITE */,
    lxb_html_tree_insertion_mode_in_row_anything_else_closed /* LXB_TAG_FECONVOLVEMATRIX */,
    lxb_html_tree_insertion_mode_in_row_anything_else_closed /* LXB_TAG_FEDIFFUSELIGHTING */,
    lxb_html_tree_insertion_mode_in_row_anything_else_closed /* LXB_TAG_FEDISPLACEMENTMAP */,
    lxb_html_tree_insertion_mode_in_row_anything_else_closed /* LXB_TAG_FEDISTANTLIGHT */,
    lxb_html_tree_insertion_mode_in_row_anything_else_closed /* LXB_TAG_FEDROPSHADOW */,
    lxb_html_tree_insertion_mode_in_row_anything_else_closed /* LXB_TAG_FEFLOOD */,
    lxb_html_tree_insertion_mode_in_row_anything_else_closed /* LXB_TAG_FEFUNCA */,
    lxb_html_tree_insertion_mode_in_row_anything_else_closed /* LXB_TAG_FEFUNCB */,
    lxb_html_tree_insertion_mode_in_row_anything_else_closed /* LXB_TAG_FEFUNCG */,
    lxb_html_tree_insertion_mode_in_row_anything_else_closed /* LXB_TAG_FEFUNCR */,
    lxb_html_tree_insertion_mode_in_row_anything_else_closed /* LXB_TAG_FEGAUSSIANBLUR */,
    lxb_html_tree_insertion_mode_in_row_anything_else_closed /* LXB_TAG_FEIMAGE */,
    lxb_html_tree_insertion_mode_in_row_anything_else_closed /* LXB_TAG_FEMERGE */,
    lxb_html_tree_insertion_mode_in_row_anything_else_closed /* LXB_TAG_FEMERGENODE */,
    lxb_html_tree_insertion_mode_in_row_anything_else_closed /* LXB_TAG_FEMORPHOLOGY */,
    lxb_html_tree_insertion_mode_in_row_anything_else_closed /* LXB_TAG_FEOFFSET */,
    lxb_html_tree_insertion_mode_in_row_anything_else_closed /* LXB_TAG_FEPOINTLIGHT */,
    lxb_html_tree_insertion_mode_in_row_anything_else_closed /* LXB_TAG_FESPECULARLIGHTING */,
    lxb_html_tree_insertion_mode_in_row_anything_else_closed /* LXB_TAG_FESPOTLIGHT */,
    lxb_html_tree_insertion_mode_in_row_anything_else_closed /* LXB_TAG_FETILE */,
    lxb_html_tree_insertion_mode_in_row_anything_else_closed /* LXB_TAG_FETURBULENCE */,
    lxb_html_tree_insertion_mode_in_row_anything_else_closed, /* LXB_TAG_FIELDSET */
    lxb_html_tree_insertion_mode_in_row_anything_else_closed, /* LXB_TAG_FIGCAPTION */
    lxb_html_tree_insertion_mode_in_row_anything_else_closed, /* LXB_TAG_FIGURE */
    lxb_html_tree_insertion_mode_in_row_anything_else_closed, /* LXB_TAG_FONT */
    lxb_html_tree_insertion_mode_in_row_anything_else_closed, /* LXB_TAG_FOOTER */
    lxb_html_tree_insertion_mode_in_row_anything_else_closed, /* LXB_TAG_FOREIGNOBJECT */
    lxb_html_tree_insertion_mode_in_row_anything_else_closed, /* LXB_TAG_FORM */
    lxb_html_tree_insertion_mode_in_row_anything_else_closed, /* LXB_TAG_FRAME */
    lxb_html_tree_insertion_mode_in_row_anything_else_closed, /* LXB_TAG_FRAMESET */
    lxb_html_tree_insertion_mode_in_row_anything_else_closed /* LXB_TAG_GLYPHREF */,
    lxb_html_tree_insertion_mode_in_row_anything_else_closed, /* LXB_TAG_H1 */
    lxb_html_tree_insertion_mode_in_row_anything_else_closed, /* LXB_TAG_H2 */
    lxb_html_tree_insertion_mode_in_row_anything_else_closed, /* LXB_TAG_H3 */
    lxb_html_tree_insertion_mode_in_row_anything_else_closed, /* LXB_TAG_H4 */
    lxb_html_tree_insertion_mode_in_row_anything_else_closed, /* LXB_TAG_H5 */
    lxb_html_tree_insertion_mode_in_row_anything_else_closed, /* LXB_TAG_H6 */
    lxb_html_tree_insertion_mode_in_row_anything_else_closed, /* LXB_TAG_HEAD */
    lxb_html_tree_insertion_mode_in_row_anything_else_closed, /* LXB_TAG_HEADER */
    lxb_html_tree_insertion_mode_in_row_anything_else_closed, /* LXB_TAG_HGROUP */
    lxb_html_tree_insertion_mode_in_row_anything_else_closed, /* LXB_TAG_HR */
    lxb_html_tree_insertion_mode_in_row_bcht_closed, /* LXB_TAG_HTML */
    lxb_html_tree_insertion_mode_in_row_anything_else_closed, /* LXB_TAG_I */
    lxb_html_tree_insertion_mode_in_row_anything_else_closed, /* LXB_TAG_IFRAME */
    lxb_html_tree_insertion_mode_in_row_anything_else_closed, /* LXB_TAG_IMAGE */
    lxb_html_tree_insertion_mode_in_row_anything_else_closed, /* LXB_TAG_IMG */
    lxb_html_tree_insertion_mode_in_row_anything_else_closed, /* LXB_TAG_INPUT */
    lxb_html_tree_insertion_mode_in_row_anything_else_closed, /* LXB_TAG_INS */
    lxb_html_tree_insertion_mode_in_row_anything_else_closed, /* LXB_TAG_ISINDEX */
    lxb_html_tree_insertion_mode_in_row_anything_else_closed, /* LXB_TAG_KBD */
    lxb_html_tree_insertion_mode_in_row_anything_else_closed, /* LXB_TAG_KEYGEN */
    lxb_html_tree_insertion_mode_in_row_anything_else_closed, /* LXB_TAG_LABEL */
    lxb_html_tree_insertion_mode_in_row_anything_else_closed, /* LXB_TAG_LEGEND */
    lxb_html_tree_insertion_mode_in_row_anything_else_closed, /* LXB_TAG_LI */
    lxb_html_tree_insertion_mode_in_row_anything_else_closed /* LXB_TAG_LINEARGRADIENT */,
    lxb_html_tree_insertion_mode_in_row_anything_else_closed, /* LXB_TAG_LINK */
    lxb_html_tree_insertion_mode_in_row_anything_else_closed, /* LXB_TAG_LISTING */
    lxb_html_tree_insertion_mode_in_row_anything_else_closed, /* LXB_TAG_MAIN */
    lxb_html_tree_insertion_mode_in_row_anything_else_closed, /* LXB_TAG_MALIGNMARK */
    lxb_html_tree_insertion_mode_in_row_anything_else_closed, /* LXB_TAG_MAP */
    lxb_html_tree_insertion_mode_in_row_anything_else_closed, /* LXB_TAG_MARK */
    lxb_html_tree_insertion_mode_in_row_anything_else_closed, /* LXB_TAG_MARQUEE */
    lxb_html_tree_insertion_mode_in_row_anything_else_closed, /* LXB_TAG_MATH */
    lxb_html_tree_insertion_mode_in_row_anything_else_closed, /* LXB_TAG_MENU */
    lxb_html_tree_insertion_mode_in_row_anything_else_closed, /* LXB_TAG_META */
    lxb_html_tree_insertion_mode_in_row_anything_else_closed, /* LXB_TAG_METER */
    lxb_html_tree_insertion_mode_in_row_anything_else_closed, /* LXB_TAG_MFENCED */
    lxb_html_tree_insertion_mode_in_row_anything_else_closed, /* LXB_TAG_MGLYPH */
    lxb_html_tree_insertion_mode_in_row_anything_else_closed, /* LXB_TAG_MI */
    lxb_html_tree_insertion_mode_in_row_anything_else_closed, /* LXB_TAG_MN */
    lxb_html_tree_insertion_mode_in_row_anything_else_closed, /* LXB_TAG_MO */
    lxb_html_tree_insertion_mode_in_row_anything_else_closed, /* LXB_TAG_MS */
    lxb_html_tree_insertion_mode_in_row_anything_else_closed, /* LXB_TAG_MTEXT */
    lxb_html_tree_insertion_mode_in_row_anything_else_closed, /* LXB_TAG_MULTICOL */
    lxb_html_tree_insertion_mode_in_row_anything_else_closed, /* LXB_TAG_NAV */
    lxb_html_tree_insertion_mode_in_row_anything_else_closed, /* LXB_TAG_NEXTID */
    lxb_html_tree_insertion_mode_in_row_anything_else_closed, /* LXB_TAG_NOBR */
    lxb_html_tree_insertion_mode_in_row_anything_else_closed, /* LXB_TAG_NOEMBED */
    lxb_html_tree_insertion_mode_in_row_anything_else_closed, /* LXB_TAG_NOFRAMES */
    lxb_html_tree_insertion_mode_in_row_anything_else_closed, /* LXB_TAG_NOSCRIPT */
    lxb_html_tree_insertion_mode_in_row_anything_else_closed, /* LXB_TAG_OBJECT */
    lxb_html_tree_insertion_mode_in_row_anything_else_closed, /* LXB_TAG_OL */
    lxb_html_tree_insertion_mode_in_row_anything_else_closed, /* LXB_TAG_OPTGROUP */
    lxb_html_tree_insertion_mode_in_row_anything_else_closed, /* LXB_TAG_OPTION */
    lxb_html_tree_insertion_mode_in_row_anything_else_closed, /* LXB_TAG_OUTPUT */
    lxb_html_tree_insertion_mode_in_row_anything_else_closed, /* LXB_TAG_P */
    lxb_html_tree_insertion_mode_in_row_anything_else_closed, /* LXB_TAG_PARAM */
    lxb_html_tree_insertion_mode_in_row_anything_else_closed, /* LXB_TAG_PATH */
    lxb_html_tree_insertion_mode_in_row_anything_else_closed, /* LXB_TAG_PICTURE */
    lxb_html_tree_insertion_mode_in_row_anything_else_closed, /* LXB_TAG_PLAINTEXT */
    lxb_html_tree_insertion_mode_in_row_anything_else_closed, /* LXB_TAG_PRE */
    lxb_html_tree_insertion_mode_in_row_anything_else_closed, /* LXB_TAG_PROGRESS */
    lxb_html_tree_insertion_mode_in_row_anything_else_closed, /* LXB_TAG_Q */
    lxb_html_tree_insertion_mode_in_row_anything_else_closed /* LXB_TAG_RADIALGRADIENT */,
    lxb_html_tree_insertion_mode_in_row_anything_else_closed, /* LXB_TAG_RB */
    lxb_html_tree_insertion_mode_in_row_anything_else_closed, /* LXB_TAG_RP */
    lxb_html_tree_insertion_mode_in_row_anything_else_closed, /* LXB_TAG_RT */
    lxb_html_tree_insertion_mode_in_row_anything_else_closed, /* LXB_TAG_RTC */
    lxb_html_tree_insertion_mode_in_row_anything_else_closed, /* LXB_TAG_RUBY */
    lxb_html_tree_insertion_mode_in_row_anything_else_closed, /* LXB_TAG_S */
    lxb_html_tree_insertion_mode_in_row_anything_else_closed, /* LXB_TAG_SAMP */
    lxb_html_tree_insertion_mode_in_row_anything_else_closed, /* LXB_TAG_SCRIPT */
    lxb_html_tree_insertion_mode_in_row_anything_else_closed, /* LXB_TAG_SECTION */
    lxb_html_tree_insertion_mode_in_row_anything_else_closed, /* LXB_TAG_SELECT */
    lxb_html_tree_insertion_mode_in_row_anything_else_closed, /* LXB_TAG_SLOT */
    lxb_html_tree_insertion_mode_in_row_anything_else_closed, /* LXB_TAG_SMALL */
    lxb_html_tree_insertion_mode_in_row_anything_else_closed, /* LXB_TAG_SOURCE */
    lxb_html_tree_insertion_mode_in_row_anything_else_closed, /* LXB_TAG_SPACER */
    lxb_html_tree_insertion_mode_in_row_anything_else_closed, /* LXB_TAG_SPAN */
    lxb_html_tree_insertion_mode_in_row_anything_else_closed, /* LXB_TAG_STRIKE */
    lxb_html_tree_insertion_mode_in_row_anything_else_closed, /* LXB_TAG_STRONG */
    lxb_html_tree_insertion_mode_in_row_anything_else_closed, /* LXB_TAG_STYLE */
    lxb_html_tree_insertion_mode_in_row_anything_else_closed, /* LXB_TAG_SUB */
    lxb_html_tree_insertion_mode_in_row_anything_else_closed, /* LXB_TAG_SUMMARY */
    lxb_html_tree_insertion_mode_in_row_anything_else_closed, /* LXB_TAG_SUP */
    lxb_html_tree_insertion_mode_in_row_anything_else_closed, /* LXB_TAG_SVG */
    lxb_html_tree_insertion_mode_in_row_ct_open_closed, /* LXB_TAG_TABLE */
    lxb_html_tree_insertion_mode_in_row_tbtfth_closed, /* LXB_TAG_TBODY */
    lxb_html_tree_insertion_mode_in_row_bcht_closed, /* LXB_TAG_TD */
    lxb_html_tree_insertion_mode_in_row_anything_else_closed, /* LXB_TAG_TEMPLATE */
    lxb_html_tree_insertion_mode_in_row_anything_else_closed, /* LXB_TAG_TEXTAREA */
    lxb_html_tree_insertion_mode_in_row_anything_else_closed /* LXB_TAG_TEXTPATH */,
    lxb_html_tree_insertion_mode_in_row_tbtfth_closed, /* LXB_TAG_TFOOT */
    lxb_html_tree_insertion_mode_in_row_bcht_closed, /* LXB_TAG_TH */
    lxb_html_tree_insertion_mode_in_row_tbtfth_closed, /* LXB_TAG_THEAD */
    lxb_html_tree_insertion_mode_in_row_anything_else_closed, /* LXB_TAG_TIME */
    lxb_html_tree_insertion_mode_in_row_anything_else_closed, /* LXB_TAG_TITLE */
    lxb_html_tree_insertion_mode_in_row_tr_closed, /* LXB_TAG_TR */
    lxb_html_tree_insertion_mode_in_row_anything_else_closed, /* LXB_TAG_TRACK */
    lxb_html_tree_insertion_mode_in_row_anything_else_closed, /* LXB_TAG_TT */
    lxb_html_tree_insertion_mode_in_row_anything_else_closed, /* LXB_TAG_U */
    lxb_html_tree_insertion_mode_in_row_anything_else_closed, /* LXB_TAG_UL */
    lxb_html_tree_insertion_mode_in_row_anything_else_closed, /* LXB_TAG_VAR */
    lxb_html_tree_insertion_mode_in_row_anything_else_closed, /* LXB_TAG_VIDEO */
    lxb_html_tree_insertion_mode_in_row_anything_else_closed, /* LXB_TAG_WBR */
    lxb_html_tree_insertion_mode_in_row_anything_else_closed  /* LXB_TAG_XMP */
};


#endif /* LXB_HTML_TREE_INSERTION_MODE_IN_ROW_H */
