/*
 * Copyright (C) 2018 Alexander Borisov
 *
 * Author: Alexander Borisov <lex.borisov@gmail.com>
 */

#ifndef LXB_HTML_TREE_INSERTION_MODE_IN_TABLE_BODY_H
#define LXB_HTML_TREE_INSERTION_MODE_IN_TABLE_BODY_H

#ifdef LXB_HTML_TAG_CONST_VERSION
#ifndef LXB_HTML_TAG_CONST_VERSION_05F7D41CB8640B01995E3DB66C13F365
#error Mismatched tags version! See "lexbor/html/tag_const.h".
#endif /* LXB_HTML_TAG_CONST_VERSION_05F7D41CB8640B01995E3DB66C13F365 */
#else
#error You need to include "lexbor/html/tag_const.h".
#endif /* LXB_HTML_TAG_CONST_VERSION */


static const lxb_html_tree_insertion_mode_f
lxb_html_tree_insertion_mode_in_table_body_res[] = 
{
    lxb_html_tree_insertion_mode_in_table_body_anything_else, /* LXB_HTML_TAG__UNDEF */
    lxb_html_tree_insertion_mode_in_table_body_anything_else, /* LXB_HTML_TAG__END_OF_FILE */
    lxb_html_tree_insertion_mode_in_table_body_anything_else, /* LXB_HTML_TAG__TEXT */
    lxb_html_tree_insertion_mode_in_table_body_anything_else, /* LXB_HTML_TAG__DOCUMENT */
    lxb_html_tree_insertion_mode_in_table_body_anything_else, /* LXB_HTML_TAG__EM_COMMENT */
    lxb_html_tree_insertion_mode_in_table_body_anything_else, /* LXB_HTML_TAG__EM_DOCTYPE */
    lxb_html_tree_insertion_mode_in_table_body_anything_else, /* LXB_HTML_TAG_A */
    lxb_html_tree_insertion_mode_in_table_body_anything_else, /* LXB_HTML_TAG_ABBR */
    lxb_html_tree_insertion_mode_in_table_body_anything_else, /* LXB_HTML_TAG_ACRONYM */
    lxb_html_tree_insertion_mode_in_table_body_anything_else, /* LXB_HTML_TAG_ADDRESS */
    lxb_html_tree_insertion_mode_in_table_body_anything_else, /* LXB_HTML_TAG_ANNOTATION_XML */
    lxb_html_tree_insertion_mode_in_table_body_anything_else, /* LXB_HTML_TAG_APPLET */
    lxb_html_tree_insertion_mode_in_table_body_anything_else, /* LXB_HTML_TAG_AREA */
    lxb_html_tree_insertion_mode_in_table_body_anything_else, /* LXB_HTML_TAG_ARTICLE */
    lxb_html_tree_insertion_mode_in_table_body_anything_else, /* LXB_HTML_TAG_ASIDE */
    lxb_html_tree_insertion_mode_in_table_body_anything_else, /* LXB_HTML_TAG_AUDIO */
    lxb_html_tree_insertion_mode_in_table_body_anything_else, /* LXB_HTML_TAG_B */
    lxb_html_tree_insertion_mode_in_table_body_anything_else, /* LXB_HTML_TAG_BASE */
    lxb_html_tree_insertion_mode_in_table_body_anything_else, /* LXB_HTML_TAG_BASEFONT */
    lxb_html_tree_insertion_mode_in_table_body_anything_else, /* LXB_HTML_TAG_BDI */
    lxb_html_tree_insertion_mode_in_table_body_anything_else, /* LXB_HTML_TAG_BDO */
    lxb_html_tree_insertion_mode_in_table_body_anything_else, /* LXB_HTML_TAG_BGSOUND */
    lxb_html_tree_insertion_mode_in_table_body_anything_else, /* LXB_HTML_TAG_BIG */
    lxb_html_tree_insertion_mode_in_table_body_anything_else, /* LXB_HTML_TAG_BLINK */
    lxb_html_tree_insertion_mode_in_table_body_anything_else, /* LXB_HTML_TAG_BLOCKQUOTE */
    lxb_html_tree_insertion_mode_in_table_body_anything_else, /* LXB_HTML_TAG_BODY */
    lxb_html_tree_insertion_mode_in_table_body_anything_else, /* LXB_HTML_TAG_BR */
    lxb_html_tree_insertion_mode_in_table_body_anything_else, /* LXB_HTML_TAG_BUTTON */
    lxb_html_tree_insertion_mode_in_table_body_anything_else, /* LXB_HTML_TAG_CANVAS */
    lxb_html_tree_insertion_mode_in_table_body_ct_open_closed, /* LXB_HTML_TAG_CAPTION */
    lxb_html_tree_insertion_mode_in_table_body_anything_else, /* LXB_HTML_TAG_CENTER */
    lxb_html_tree_insertion_mode_in_table_body_anything_else, /* LXB_HTML_TAG_CITE */
    lxb_html_tree_insertion_mode_in_table_body_anything_else, /* LXB_HTML_TAG_CODE */
    lxb_html_tree_insertion_mode_in_table_body_ct_open_closed, /* LXB_HTML_TAG_COL */
    lxb_html_tree_insertion_mode_in_table_body_ct_open_closed, /* LXB_HTML_TAG_COLGROUP */
    lxb_html_tree_insertion_mode_in_table_body_anything_else, /* LXB_HTML_TAG_DATA */
    lxb_html_tree_insertion_mode_in_table_body_anything_else, /* LXB_HTML_TAG_DATALIST */
    lxb_html_tree_insertion_mode_in_table_body_anything_else, /* LXB_HTML_TAG_DD */
    lxb_html_tree_insertion_mode_in_table_body_anything_else, /* LXB_HTML_TAG_DEL */
    lxb_html_tree_insertion_mode_in_table_body_anything_else, /* LXB_HTML_TAG_DESC */
    lxb_html_tree_insertion_mode_in_table_body_anything_else, /* LXB_HTML_TAG_DETAILS */
    lxb_html_tree_insertion_mode_in_table_body_anything_else, /* LXB_HTML_TAG_DFN */
    lxb_html_tree_insertion_mode_in_table_body_anything_else, /* LXB_HTML_TAG_DIALOG */
    lxb_html_tree_insertion_mode_in_table_body_anything_else, /* LXB_HTML_TAG_DIR */
    lxb_html_tree_insertion_mode_in_table_body_anything_else, /* LXB_HTML_TAG_DIV */
    lxb_html_tree_insertion_mode_in_table_body_anything_else, /* LXB_HTML_TAG_DL */
    lxb_html_tree_insertion_mode_in_table_body_anything_else, /* LXB_HTML_TAG_DT */
    lxb_html_tree_insertion_mode_in_table_body_anything_else, /* LXB_HTML_TAG_EM */
    lxb_html_tree_insertion_mode_in_table_body_anything_else, /* LXB_HTML_TAG_EMBED */
    lxb_html_tree_insertion_mode_in_table_body_anything_else, /* LXB_HTML_TAG_FIELDSET */
    lxb_html_tree_insertion_mode_in_table_body_anything_else, /* LXB_HTML_TAG_FIGCAPTION */
    lxb_html_tree_insertion_mode_in_table_body_anything_else, /* LXB_HTML_TAG_FIGURE */
    lxb_html_tree_insertion_mode_in_table_body_anything_else, /* LXB_HTML_TAG_FONT */
    lxb_html_tree_insertion_mode_in_table_body_anything_else, /* LXB_HTML_TAG_FOOTER */
    lxb_html_tree_insertion_mode_in_table_body_anything_else, /* LXB_HTML_TAG_FOREIGNOBJECT */
    lxb_html_tree_insertion_mode_in_table_body_anything_else, /* LXB_HTML_TAG_FORM */
    lxb_html_tree_insertion_mode_in_table_body_anything_else, /* LXB_HTML_TAG_FRAME */
    lxb_html_tree_insertion_mode_in_table_body_anything_else, /* LXB_HTML_TAG_FRAMESET */
    lxb_html_tree_insertion_mode_in_table_body_anything_else, /* LXB_HTML_TAG_H1 */
    lxb_html_tree_insertion_mode_in_table_body_anything_else, /* LXB_HTML_TAG_H2 */
    lxb_html_tree_insertion_mode_in_table_body_anything_else, /* LXB_HTML_TAG_H3 */
    lxb_html_tree_insertion_mode_in_table_body_anything_else, /* LXB_HTML_TAG_H4 */
    lxb_html_tree_insertion_mode_in_table_body_anything_else, /* LXB_HTML_TAG_H5 */
    lxb_html_tree_insertion_mode_in_table_body_anything_else, /* LXB_HTML_TAG_H6 */
    lxb_html_tree_insertion_mode_in_table_body_anything_else, /* LXB_HTML_TAG_HEAD */
    lxb_html_tree_insertion_mode_in_table_body_anything_else, /* LXB_HTML_TAG_HEADER */
    lxb_html_tree_insertion_mode_in_table_body_anything_else, /* LXB_HTML_TAG_HGROUP */
    lxb_html_tree_insertion_mode_in_table_body_anything_else, /* LXB_HTML_TAG_HR */
    lxb_html_tree_insertion_mode_in_table_body_anything_else, /* LXB_HTML_TAG_HTML */
    lxb_html_tree_insertion_mode_in_table_body_anything_else, /* LXB_HTML_TAG_I */
    lxb_html_tree_insertion_mode_in_table_body_anything_else, /* LXB_HTML_TAG_IFRAME */
    lxb_html_tree_insertion_mode_in_table_body_anything_else, /* LXB_HTML_TAG_IMAGE */
    lxb_html_tree_insertion_mode_in_table_body_anything_else, /* LXB_HTML_TAG_IMG */
    lxb_html_tree_insertion_mode_in_table_body_anything_else, /* LXB_HTML_TAG_INPUT */
    lxb_html_tree_insertion_mode_in_table_body_anything_else, /* LXB_HTML_TAG_INS */
    lxb_html_tree_insertion_mode_in_table_body_anything_else, /* LXB_HTML_TAG_ISINDEX */
    lxb_html_tree_insertion_mode_in_table_body_anything_else, /* LXB_HTML_TAG_KBD */
    lxb_html_tree_insertion_mode_in_table_body_anything_else, /* LXB_HTML_TAG_KEYGEN */
    lxb_html_tree_insertion_mode_in_table_body_anything_else, /* LXB_HTML_TAG_LABEL */
    lxb_html_tree_insertion_mode_in_table_body_anything_else, /* LXB_HTML_TAG_LEGEND */
    lxb_html_tree_insertion_mode_in_table_body_anything_else, /* LXB_HTML_TAG_LI */
    lxb_html_tree_insertion_mode_in_table_body_anything_else, /* LXB_HTML_TAG_LINK */
    lxb_html_tree_insertion_mode_in_table_body_anything_else, /* LXB_HTML_TAG_LISTING */
    lxb_html_tree_insertion_mode_in_table_body_anything_else, /* LXB_HTML_TAG_MAIN */
    lxb_html_tree_insertion_mode_in_table_body_anything_else, /* LXB_HTML_TAG_MALIGNMARK */
    lxb_html_tree_insertion_mode_in_table_body_anything_else, /* LXB_HTML_TAG_MAP */
    lxb_html_tree_insertion_mode_in_table_body_anything_else, /* LXB_HTML_TAG_MARK */
    lxb_html_tree_insertion_mode_in_table_body_anything_else, /* LXB_HTML_TAG_MARQUEE */
    lxb_html_tree_insertion_mode_in_table_body_anything_else, /* LXB_HTML_TAG_MATH */
    lxb_html_tree_insertion_mode_in_table_body_anything_else, /* LXB_HTML_TAG_MENU */
    lxb_html_tree_insertion_mode_in_table_body_anything_else, /* LXB_HTML_TAG_META */
    lxb_html_tree_insertion_mode_in_table_body_anything_else, /* LXB_HTML_TAG_METER */
    lxb_html_tree_insertion_mode_in_table_body_anything_else, /* LXB_HTML_TAG_MFENCED */
    lxb_html_tree_insertion_mode_in_table_body_anything_else, /* LXB_HTML_TAG_MGLYPH */
    lxb_html_tree_insertion_mode_in_table_body_anything_else, /* LXB_HTML_TAG_MI */
    lxb_html_tree_insertion_mode_in_table_body_anything_else, /* LXB_HTML_TAG_MN */
    lxb_html_tree_insertion_mode_in_table_body_anything_else, /* LXB_HTML_TAG_MO */
    lxb_html_tree_insertion_mode_in_table_body_anything_else, /* LXB_HTML_TAG_MS */
    lxb_html_tree_insertion_mode_in_table_body_anything_else, /* LXB_HTML_TAG_MTEXT */
    lxb_html_tree_insertion_mode_in_table_body_anything_else, /* LXB_HTML_TAG_MULTICOL */
    lxb_html_tree_insertion_mode_in_table_body_anything_else, /* LXB_HTML_TAG_NAV */
    lxb_html_tree_insertion_mode_in_table_body_anything_else, /* LXB_HTML_TAG_NEXTID */
    lxb_html_tree_insertion_mode_in_table_body_anything_else, /* LXB_HTML_TAG_NOBR */
    lxb_html_tree_insertion_mode_in_table_body_anything_else, /* LXB_HTML_TAG_NOEMBED */
    lxb_html_tree_insertion_mode_in_table_body_anything_else, /* LXB_HTML_TAG_NOFRAMES */
    lxb_html_tree_insertion_mode_in_table_body_anything_else, /* LXB_HTML_TAG_NOSCRIPT */
    lxb_html_tree_insertion_mode_in_table_body_anything_else, /* LXB_HTML_TAG_OBJECT */
    lxb_html_tree_insertion_mode_in_table_body_anything_else, /* LXB_HTML_TAG_OL */
    lxb_html_tree_insertion_mode_in_table_body_anything_else, /* LXB_HTML_TAG_OPTGROUP */
    lxb_html_tree_insertion_mode_in_table_body_anything_else, /* LXB_HTML_TAG_OPTION */
    lxb_html_tree_insertion_mode_in_table_body_anything_else, /* LXB_HTML_TAG_OUTPUT */
    lxb_html_tree_insertion_mode_in_table_body_anything_else, /* LXB_HTML_TAG_P */
    lxb_html_tree_insertion_mode_in_table_body_anything_else, /* LXB_HTML_TAG_PARAM */
    lxb_html_tree_insertion_mode_in_table_body_anything_else, /* LXB_HTML_TAG_PATH */
    lxb_html_tree_insertion_mode_in_table_body_anything_else, /* LXB_HTML_TAG_PICTURE */
    lxb_html_tree_insertion_mode_in_table_body_anything_else, /* LXB_HTML_TAG_PLAINTEXT */
    lxb_html_tree_insertion_mode_in_table_body_anything_else, /* LXB_HTML_TAG_PRE */
    lxb_html_tree_insertion_mode_in_table_body_anything_else, /* LXB_HTML_TAG_PROGRESS */
    lxb_html_tree_insertion_mode_in_table_body_anything_else, /* LXB_HTML_TAG_Q */
    lxb_html_tree_insertion_mode_in_table_body_anything_else, /* LXB_HTML_TAG_RB */
    lxb_html_tree_insertion_mode_in_table_body_anything_else, /* LXB_HTML_TAG_RP */
    lxb_html_tree_insertion_mode_in_table_body_anything_else, /* LXB_HTML_TAG_RT */
    lxb_html_tree_insertion_mode_in_table_body_anything_else, /* LXB_HTML_TAG_RTC */
    lxb_html_tree_insertion_mode_in_table_body_anything_else, /* LXB_HTML_TAG_RUBY */
    lxb_html_tree_insertion_mode_in_table_body_anything_else, /* LXB_HTML_TAG_S */
    lxb_html_tree_insertion_mode_in_table_body_anything_else, /* LXB_HTML_TAG_SAMP */
    lxb_html_tree_insertion_mode_in_table_body_anything_else, /* LXB_HTML_TAG_SCRIPT */
    lxb_html_tree_insertion_mode_in_table_body_anything_else, /* LXB_HTML_TAG_SECTION */
    lxb_html_tree_insertion_mode_in_table_body_anything_else, /* LXB_HTML_TAG_SELECT */
    lxb_html_tree_insertion_mode_in_table_body_anything_else, /* LXB_HTML_TAG_SLOT */
    lxb_html_tree_insertion_mode_in_table_body_anything_else, /* LXB_HTML_TAG_SMALL */
    lxb_html_tree_insertion_mode_in_table_body_anything_else, /* LXB_HTML_TAG_SOURCE */
    lxb_html_tree_insertion_mode_in_table_body_anything_else, /* LXB_HTML_TAG_SPACER */
    lxb_html_tree_insertion_mode_in_table_body_anything_else, /* LXB_HTML_TAG_SPAN */
    lxb_html_tree_insertion_mode_in_table_body_anything_else, /* LXB_HTML_TAG_STRIKE */
    lxb_html_tree_insertion_mode_in_table_body_anything_else, /* LXB_HTML_TAG_STRONG */
    lxb_html_tree_insertion_mode_in_table_body_anything_else, /* LXB_HTML_TAG_STYLE */
    lxb_html_tree_insertion_mode_in_table_body_anything_else, /* LXB_HTML_TAG_SUB */
    lxb_html_tree_insertion_mode_in_table_body_anything_else, /* LXB_HTML_TAG_SUMMARY */
    lxb_html_tree_insertion_mode_in_table_body_anything_else, /* LXB_HTML_TAG_SUP */
    lxb_html_tree_insertion_mode_in_table_body_anything_else, /* LXB_HTML_TAG_SVG */
    lxb_html_tree_insertion_mode_in_table_body_anything_else, /* LXB_HTML_TAG_TABLE */
    lxb_html_tree_insertion_mode_in_table_body_ct_open_closed, /* LXB_HTML_TAG_TBODY */
    lxb_html_tree_insertion_mode_in_table_body_thtd, /* LXB_HTML_TAG_TD */
    lxb_html_tree_insertion_mode_in_table_body_anything_else, /* LXB_HTML_TAG_TEMPLATE */
    lxb_html_tree_insertion_mode_in_table_body_anything_else, /* LXB_HTML_TAG_TEXTAREA */
    lxb_html_tree_insertion_mode_in_table_body_ct_open_closed, /* LXB_HTML_TAG_TFOOT */
    lxb_html_tree_insertion_mode_in_table_body_thtd, /* LXB_HTML_TAG_TH */
    lxb_html_tree_insertion_mode_in_table_body_ct_open_closed, /* LXB_HTML_TAG_THEAD */
    lxb_html_tree_insertion_mode_in_table_body_anything_else, /* LXB_HTML_TAG_TIME */
    lxb_html_tree_insertion_mode_in_table_body_anything_else, /* LXB_HTML_TAG_TITLE */
    lxb_html_tree_insertion_mode_in_table_body_tr, /* LXB_HTML_TAG_TR */
    lxb_html_tree_insertion_mode_in_table_body_anything_else, /* LXB_HTML_TAG_TRACK */
    lxb_html_tree_insertion_mode_in_table_body_anything_else, /* LXB_HTML_TAG_TT */
    lxb_html_tree_insertion_mode_in_table_body_anything_else, /* LXB_HTML_TAG_U */
    lxb_html_tree_insertion_mode_in_table_body_anything_else, /* LXB_HTML_TAG_UL */
    lxb_html_tree_insertion_mode_in_table_body_anything_else, /* LXB_HTML_TAG_VAR */
    lxb_html_tree_insertion_mode_in_table_body_anything_else, /* LXB_HTML_TAG_VIDEO */
    lxb_html_tree_insertion_mode_in_table_body_anything_else, /* LXB_HTML_TAG_WBR */
    lxb_html_tree_insertion_mode_in_table_body_anything_else  /* LXB_HTML_TAG_XMP */
};

static const lxb_html_tree_insertion_mode_f
lxb_html_tree_insertion_mode_in_table_body_closed_res[] =
{
    lxb_html_tree_insertion_mode_in_table_body_anything_else_closed, /* LXB_HTML_TAG__UNDEF */
    lxb_html_tree_insertion_mode_in_table_body_anything_else_closed, /* LXB_HTML_TAG__END_OF_FILE */
    lxb_html_tree_insertion_mode_in_table_body_anything_else_closed, /* LXB_HTML_TAG__TEXT */
    lxb_html_tree_insertion_mode_in_table_body_anything_else_closed, /* LXB_HTML_TAG__DOCUMENT */
    lxb_html_tree_insertion_mode_in_table_body_anything_else_closed, /* LXB_HTML_TAG__EM_COMMENT */
    lxb_html_tree_insertion_mode_in_table_body_anything_else_closed, /* LXB_HTML_TAG__EM_DOCTYPE */
    lxb_html_tree_insertion_mode_in_table_body_anything_else_closed, /* LXB_HTML_TAG_A */
    lxb_html_tree_insertion_mode_in_table_body_anything_else_closed, /* LXB_HTML_TAG_ABBR */
    lxb_html_tree_insertion_mode_in_table_body_anything_else_closed, /* LXB_HTML_TAG_ACRONYM */
    lxb_html_tree_insertion_mode_in_table_body_anything_else_closed, /* LXB_HTML_TAG_ADDRESS */
    lxb_html_tree_insertion_mode_in_table_body_anything_else_closed, /* LXB_HTML_TAG_ANNOTATION_XML */
    lxb_html_tree_insertion_mode_in_table_body_anything_else_closed, /* LXB_HTML_TAG_APPLET */
    lxb_html_tree_insertion_mode_in_table_body_anything_else_closed, /* LXB_HTML_TAG_AREA */
    lxb_html_tree_insertion_mode_in_table_body_anything_else_closed, /* LXB_HTML_TAG_ARTICLE */
    lxb_html_tree_insertion_mode_in_table_body_anything_else_closed, /* LXB_HTML_TAG_ASIDE */
    lxb_html_tree_insertion_mode_in_table_body_anything_else_closed, /* LXB_HTML_TAG_AUDIO */
    lxb_html_tree_insertion_mode_in_table_body_anything_else_closed, /* LXB_HTML_TAG_B */
    lxb_html_tree_insertion_mode_in_table_body_anything_else_closed, /* LXB_HTML_TAG_BASE */
    lxb_html_tree_insertion_mode_in_table_body_anything_else_closed, /* LXB_HTML_TAG_BASEFONT */
    lxb_html_tree_insertion_mode_in_table_body_anything_else_closed, /* LXB_HTML_TAG_BDI */
    lxb_html_tree_insertion_mode_in_table_body_anything_else_closed, /* LXB_HTML_TAG_BDO */
    lxb_html_tree_insertion_mode_in_table_body_anything_else_closed, /* LXB_HTML_TAG_BGSOUND */
    lxb_html_tree_insertion_mode_in_table_body_anything_else_closed, /* LXB_HTML_TAG_BIG */
    lxb_html_tree_insertion_mode_in_table_body_anything_else_closed, /* LXB_HTML_TAG_BLINK */
    lxb_html_tree_insertion_mode_in_table_body_anything_else_closed, /* LXB_HTML_TAG_BLOCKQUOTE */
    lxb_html_tree_insertion_mode_in_table_body_bcht_closed, /* LXB_HTML_TAG_BODY */
    lxb_html_tree_insertion_mode_in_table_body_anything_else_closed, /* LXB_HTML_TAG_BR */
    lxb_html_tree_insertion_mode_in_table_body_anything_else_closed, /* LXB_HTML_TAG_BUTTON */
    lxb_html_tree_insertion_mode_in_table_body_anything_else_closed, /* LXB_HTML_TAG_CANVAS */
    lxb_html_tree_insertion_mode_in_table_body_bcht_closed, /* LXB_HTML_TAG_CAPTION */
    lxb_html_tree_insertion_mode_in_table_body_anything_else_closed, /* LXB_HTML_TAG_CENTER */
    lxb_html_tree_insertion_mode_in_table_body_anything_else_closed, /* LXB_HTML_TAG_CITE */
    lxb_html_tree_insertion_mode_in_table_body_anything_else_closed, /* LXB_HTML_TAG_CODE */
    lxb_html_tree_insertion_mode_in_table_body_bcht_closed, /* LXB_HTML_TAG_COL */
    lxb_html_tree_insertion_mode_in_table_body_bcht_closed, /* LXB_HTML_TAG_COLGROUP */
    lxb_html_tree_insertion_mode_in_table_body_anything_else_closed, /* LXB_HTML_TAG_DATA */
    lxb_html_tree_insertion_mode_in_table_body_anything_else_closed, /* LXB_HTML_TAG_DATALIST */
    lxb_html_tree_insertion_mode_in_table_body_anything_else_closed, /* LXB_HTML_TAG_DD */
    lxb_html_tree_insertion_mode_in_table_body_anything_else_closed, /* LXB_HTML_TAG_DEL */
    lxb_html_tree_insertion_mode_in_table_body_anything_else_closed, /* LXB_HTML_TAG_DESC */
    lxb_html_tree_insertion_mode_in_table_body_anything_else_closed, /* LXB_HTML_TAG_DETAILS */
    lxb_html_tree_insertion_mode_in_table_body_anything_else_closed, /* LXB_HTML_TAG_DFN */
    lxb_html_tree_insertion_mode_in_table_body_anything_else_closed, /* LXB_HTML_TAG_DIALOG */
    lxb_html_tree_insertion_mode_in_table_body_anything_else_closed, /* LXB_HTML_TAG_DIR */
    lxb_html_tree_insertion_mode_in_table_body_anything_else_closed, /* LXB_HTML_TAG_DIV */
    lxb_html_tree_insertion_mode_in_table_body_anything_else_closed, /* LXB_HTML_TAG_DL */
    lxb_html_tree_insertion_mode_in_table_body_anything_else_closed, /* LXB_HTML_TAG_DT */
    lxb_html_tree_insertion_mode_in_table_body_anything_else_closed, /* LXB_HTML_TAG_EM */
    lxb_html_tree_insertion_mode_in_table_body_anything_else_closed, /* LXB_HTML_TAG_EMBED */
    lxb_html_tree_insertion_mode_in_table_body_anything_else_closed, /* LXB_HTML_TAG_FIELDSET */
    lxb_html_tree_insertion_mode_in_table_body_anything_else_closed, /* LXB_HTML_TAG_FIGCAPTION */
    lxb_html_tree_insertion_mode_in_table_body_anything_else_closed, /* LXB_HTML_TAG_FIGURE */
    lxb_html_tree_insertion_mode_in_table_body_anything_else_closed, /* LXB_HTML_TAG_FONT */
    lxb_html_tree_insertion_mode_in_table_body_anything_else_closed, /* LXB_HTML_TAG_FOOTER */
    lxb_html_tree_insertion_mode_in_table_body_anything_else_closed, /* LXB_HTML_TAG_FOREIGNOBJECT */
    lxb_html_tree_insertion_mode_in_table_body_anything_else_closed, /* LXB_HTML_TAG_FORM */
    lxb_html_tree_insertion_mode_in_table_body_anything_else_closed, /* LXB_HTML_TAG_FRAME */
    lxb_html_tree_insertion_mode_in_table_body_anything_else_closed, /* LXB_HTML_TAG_FRAMESET */
    lxb_html_tree_insertion_mode_in_table_body_anything_else_closed, /* LXB_HTML_TAG_H1 */
    lxb_html_tree_insertion_mode_in_table_body_anything_else_closed, /* LXB_HTML_TAG_H2 */
    lxb_html_tree_insertion_mode_in_table_body_anything_else_closed, /* LXB_HTML_TAG_H3 */
    lxb_html_tree_insertion_mode_in_table_body_anything_else_closed, /* LXB_HTML_TAG_H4 */
    lxb_html_tree_insertion_mode_in_table_body_anything_else_closed, /* LXB_HTML_TAG_H5 */
    lxb_html_tree_insertion_mode_in_table_body_anything_else_closed, /* LXB_HTML_TAG_H6 */
    lxb_html_tree_insertion_mode_in_table_body_anything_else_closed, /* LXB_HTML_TAG_HEAD */
    lxb_html_tree_insertion_mode_in_table_body_anything_else_closed, /* LXB_HTML_TAG_HEADER */
    lxb_html_tree_insertion_mode_in_table_body_anything_else_closed, /* LXB_HTML_TAG_HGROUP */
    lxb_html_tree_insertion_mode_in_table_body_anything_else_closed, /* LXB_HTML_TAG_HR */
    lxb_html_tree_insertion_mode_in_table_body_bcht_closed, /* LXB_HTML_TAG_HTML */
    lxb_html_tree_insertion_mode_in_table_body_anything_else_closed, /* LXB_HTML_TAG_I */
    lxb_html_tree_insertion_mode_in_table_body_anything_else_closed, /* LXB_HTML_TAG_IFRAME */
    lxb_html_tree_insertion_mode_in_table_body_anything_else_closed, /* LXB_HTML_TAG_IMAGE */
    lxb_html_tree_insertion_mode_in_table_body_anything_else_closed, /* LXB_HTML_TAG_IMG */
    lxb_html_tree_insertion_mode_in_table_body_anything_else_closed, /* LXB_HTML_TAG_INPUT */
    lxb_html_tree_insertion_mode_in_table_body_anything_else_closed, /* LXB_HTML_TAG_INS */
    lxb_html_tree_insertion_mode_in_table_body_anything_else_closed, /* LXB_HTML_TAG_ISINDEX */
    lxb_html_tree_insertion_mode_in_table_body_anything_else_closed, /* LXB_HTML_TAG_KBD */
    lxb_html_tree_insertion_mode_in_table_body_anything_else_closed, /* LXB_HTML_TAG_KEYGEN */
    lxb_html_tree_insertion_mode_in_table_body_anything_else_closed, /* LXB_HTML_TAG_LABEL */
    lxb_html_tree_insertion_mode_in_table_body_anything_else_closed, /* LXB_HTML_TAG_LEGEND */
    lxb_html_tree_insertion_mode_in_table_body_anything_else_closed, /* LXB_HTML_TAG_LI */
    lxb_html_tree_insertion_mode_in_table_body_anything_else_closed, /* LXB_HTML_TAG_LINK */
    lxb_html_tree_insertion_mode_in_table_body_anything_else_closed, /* LXB_HTML_TAG_LISTING */
    lxb_html_tree_insertion_mode_in_table_body_anything_else_closed, /* LXB_HTML_TAG_MAIN */
    lxb_html_tree_insertion_mode_in_table_body_anything_else_closed, /* LXB_HTML_TAG_MALIGNMARK */
    lxb_html_tree_insertion_mode_in_table_body_anything_else_closed, /* LXB_HTML_TAG_MAP */
    lxb_html_tree_insertion_mode_in_table_body_anything_else_closed, /* LXB_HTML_TAG_MARK */
    lxb_html_tree_insertion_mode_in_table_body_anything_else_closed, /* LXB_HTML_TAG_MARQUEE */
    lxb_html_tree_insertion_mode_in_table_body_anything_else_closed, /* LXB_HTML_TAG_MATH */
    lxb_html_tree_insertion_mode_in_table_body_anything_else_closed, /* LXB_HTML_TAG_MENU */
    lxb_html_tree_insertion_mode_in_table_body_anything_else_closed, /* LXB_HTML_TAG_META */
    lxb_html_tree_insertion_mode_in_table_body_anything_else_closed, /* LXB_HTML_TAG_METER */
    lxb_html_tree_insertion_mode_in_table_body_anything_else_closed, /* LXB_HTML_TAG_MFENCED */
    lxb_html_tree_insertion_mode_in_table_body_anything_else_closed, /* LXB_HTML_TAG_MGLYPH */
    lxb_html_tree_insertion_mode_in_table_body_anything_else_closed, /* LXB_HTML_TAG_MI */
    lxb_html_tree_insertion_mode_in_table_body_anything_else_closed, /* LXB_HTML_TAG_MN */
    lxb_html_tree_insertion_mode_in_table_body_anything_else_closed, /* LXB_HTML_TAG_MO */
    lxb_html_tree_insertion_mode_in_table_body_anything_else_closed, /* LXB_HTML_TAG_MS */
    lxb_html_tree_insertion_mode_in_table_body_anything_else_closed, /* LXB_HTML_TAG_MTEXT */
    lxb_html_tree_insertion_mode_in_table_body_anything_else_closed, /* LXB_HTML_TAG_MULTICOL */
    lxb_html_tree_insertion_mode_in_table_body_anything_else_closed, /* LXB_HTML_TAG_NAV */
    lxb_html_tree_insertion_mode_in_table_body_anything_else_closed, /* LXB_HTML_TAG_NEXTID */
    lxb_html_tree_insertion_mode_in_table_body_anything_else_closed, /* LXB_HTML_TAG_NOBR */
    lxb_html_tree_insertion_mode_in_table_body_anything_else_closed, /* LXB_HTML_TAG_NOEMBED */
    lxb_html_tree_insertion_mode_in_table_body_anything_else_closed, /* LXB_HTML_TAG_NOFRAMES */
    lxb_html_tree_insertion_mode_in_table_body_anything_else_closed, /* LXB_HTML_TAG_NOSCRIPT */
    lxb_html_tree_insertion_mode_in_table_body_anything_else_closed, /* LXB_HTML_TAG_OBJECT */
    lxb_html_tree_insertion_mode_in_table_body_anything_else_closed, /* LXB_HTML_TAG_OL */
    lxb_html_tree_insertion_mode_in_table_body_anything_else_closed, /* LXB_HTML_TAG_OPTGROUP */
    lxb_html_tree_insertion_mode_in_table_body_anything_else_closed, /* LXB_HTML_TAG_OPTION */
    lxb_html_tree_insertion_mode_in_table_body_anything_else_closed, /* LXB_HTML_TAG_OUTPUT */
    lxb_html_tree_insertion_mode_in_table_body_anything_else_closed, /* LXB_HTML_TAG_P */
    lxb_html_tree_insertion_mode_in_table_body_anything_else_closed, /* LXB_HTML_TAG_PARAM */
    lxb_html_tree_insertion_mode_in_table_body_anything_else_closed, /* LXB_HTML_TAG_PATH */
    lxb_html_tree_insertion_mode_in_table_body_anything_else_closed, /* LXB_HTML_TAG_PICTURE */
    lxb_html_tree_insertion_mode_in_table_body_anything_else_closed, /* LXB_HTML_TAG_PLAINTEXT */
    lxb_html_tree_insertion_mode_in_table_body_anything_else_closed, /* LXB_HTML_TAG_PRE */
    lxb_html_tree_insertion_mode_in_table_body_anything_else_closed, /* LXB_HTML_TAG_PROGRESS */
    lxb_html_tree_insertion_mode_in_table_body_anything_else_closed, /* LXB_HTML_TAG_Q */
    lxb_html_tree_insertion_mode_in_table_body_anything_else_closed, /* LXB_HTML_TAG_RB */
    lxb_html_tree_insertion_mode_in_table_body_anything_else_closed, /* LXB_HTML_TAG_RP */
    lxb_html_tree_insertion_mode_in_table_body_anything_else_closed, /* LXB_HTML_TAG_RT */
    lxb_html_tree_insertion_mode_in_table_body_anything_else_closed, /* LXB_HTML_TAG_RTC */
    lxb_html_tree_insertion_mode_in_table_body_anything_else_closed, /* LXB_HTML_TAG_RUBY */
    lxb_html_tree_insertion_mode_in_table_body_anything_else_closed, /* LXB_HTML_TAG_S */
    lxb_html_tree_insertion_mode_in_table_body_anything_else_closed, /* LXB_HTML_TAG_SAMP */
    lxb_html_tree_insertion_mode_in_table_body_anything_else_closed, /* LXB_HTML_TAG_SCRIPT */
    lxb_html_tree_insertion_mode_in_table_body_anything_else_closed, /* LXB_HTML_TAG_SECTION */
    lxb_html_tree_insertion_mode_in_table_body_anything_else_closed, /* LXB_HTML_TAG_SELECT */
    lxb_html_tree_insertion_mode_in_table_body_anything_else_closed, /* LXB_HTML_TAG_SLOT */
    lxb_html_tree_insertion_mode_in_table_body_anything_else_closed, /* LXB_HTML_TAG_SMALL */
    lxb_html_tree_insertion_mode_in_table_body_anything_else_closed, /* LXB_HTML_TAG_SOURCE */
    lxb_html_tree_insertion_mode_in_table_body_anything_else_closed, /* LXB_HTML_TAG_SPACER */
    lxb_html_tree_insertion_mode_in_table_body_anything_else_closed, /* LXB_HTML_TAG_SPAN */
    lxb_html_tree_insertion_mode_in_table_body_anything_else_closed, /* LXB_HTML_TAG_STRIKE */
    lxb_html_tree_insertion_mode_in_table_body_anything_else_closed, /* LXB_HTML_TAG_STRONG */
    lxb_html_tree_insertion_mode_in_table_body_anything_else_closed, /* LXB_HTML_TAG_STYLE */
    lxb_html_tree_insertion_mode_in_table_body_anything_else_closed, /* LXB_HTML_TAG_SUB */
    lxb_html_tree_insertion_mode_in_table_body_anything_else_closed, /* LXB_HTML_TAG_SUMMARY */
    lxb_html_tree_insertion_mode_in_table_body_anything_else_closed, /* LXB_HTML_TAG_SUP */
    lxb_html_tree_insertion_mode_in_table_body_anything_else_closed, /* LXB_HTML_TAG_SVG */
    lxb_html_tree_insertion_mode_in_table_body_ct_open_closed, /* LXB_HTML_TAG_TABLE */
    lxb_html_tree_insertion_mode_in_table_body_tbtfth_closed, /* LXB_HTML_TAG_TBODY */
    lxb_html_tree_insertion_mode_in_table_body_bcht_closed, /* LXB_HTML_TAG_TD */
    lxb_html_tree_insertion_mode_in_table_body_anything_else_closed, /* LXB_HTML_TAG_TEMPLATE */
    lxb_html_tree_insertion_mode_in_table_body_anything_else_closed, /* LXB_HTML_TAG_TEXTAREA */
    lxb_html_tree_insertion_mode_in_table_body_tbtfth_closed, /* LXB_HTML_TAG_TFOOT */
    lxb_html_tree_insertion_mode_in_table_body_bcht_closed, /* LXB_HTML_TAG_TH */
    lxb_html_tree_insertion_mode_in_table_body_tbtfth_closed, /* LXB_HTML_TAG_THEAD */
    lxb_html_tree_insertion_mode_in_table_body_anything_else_closed, /* LXB_HTML_TAG_TIME */
    lxb_html_tree_insertion_mode_in_table_body_anything_else_closed, /* LXB_HTML_TAG_TITLE */
    lxb_html_tree_insertion_mode_in_table_body_bcht_closed, /* LXB_HTML_TAG_TR */
    lxb_html_tree_insertion_mode_in_table_body_anything_else_closed, /* LXB_HTML_TAG_TRACK */
    lxb_html_tree_insertion_mode_in_table_body_anything_else_closed, /* LXB_HTML_TAG_TT */
    lxb_html_tree_insertion_mode_in_table_body_anything_else_closed, /* LXB_HTML_TAG_U */
    lxb_html_tree_insertion_mode_in_table_body_anything_else_closed, /* LXB_HTML_TAG_UL */
    lxb_html_tree_insertion_mode_in_table_body_anything_else_closed, /* LXB_HTML_TAG_VAR */
    lxb_html_tree_insertion_mode_in_table_body_anything_else_closed, /* LXB_HTML_TAG_VIDEO */
    lxb_html_tree_insertion_mode_in_table_body_anything_else_closed, /* LXB_HTML_TAG_WBR */
    lxb_html_tree_insertion_mode_in_table_body_anything_else_closed  /* LXB_HTML_TAG_XMP */
};


#endif /* LXB_HTML_TREE_INSERTION_MODE_IN_TABLE_BODY_H */
