/*
 * Copyright (C) 2019 Alexander Borisov
 *
 * Author: Alexander Borisov <borisov@lexbor.com>
 */

#include "lexbor/encoding/encoding.h"
#include "lexbor/encoding/multi.h"


#define append_to_file(fc, data, len, codepoint)                               \
    do {                                                                       \
        lxb_char_t *data_to = data;                                            \
                                                                               \
        for (size_t j = 0; j < len; j++) {                                     \
            fprintf(fc, "\\x%02X", (unsigned) data_to[j]);                     \
        }                                                                      \
                                                                               \
        fprintf(fc, " 0x%04X\n", (unsigned) codepoint);                        \
    }                                                                          \
    while (0)

#define encode_to_file(fc, ref, end, cp)                                       \
    do {                                                                       \
        memset(&ctx, 0, sizeof(lxb_encoding_encode_t));                        \
                                                                               \
        len = enc_data->encode(&ctx, &ref, end, cp);                           \
        if (len < LXB_ENCODING_ENCODE_OK) {                                    \
            printf("Failed to encoding code point: %u\n", cp);                 \
            return EXIT_FAILURE;                                               \
        }                                                                      \
                                                                               \
        ref -= len;                                                            \
                                                                               \
        if (*ref > 0x9F) {                                                     \
            break;                                                             \
        }                                                                      \
                                                                               \
        append_to_file(fc, ref, len, cp);                                      \
    }                                                                          \
    while (0)


int main(int argc, const char * argv[])
{
    int8_t len;
    size_t size;
    lxb_encoding_encode_t ctx = {0};
    const lxb_encoding_data_t *enc_data;
    const lxb_encoding_multi_index_t *entry;

    lxb_char_t data[8];
    lxb_char_t *ref = data;
    const lxb_char_t *end = data + sizeof(data);

    const char *filepath = "./shift_jis_map_decode.txt";

    enc_data = lxb_encoding_data(LXB_ENCODING_SHIFT_JIS);

    FILE *fc = fopen(filepath, "w");
    if (fc == NULL) {
        printf("Failed to opening file: %s\n", filepath);
        exit(EXIT_FAILURE);
    }

    fprintf(fc, "#\n"
            "# Copyright (C) 2019 Alexander Borisov\n"
            "#\n"
            "# Author: Alexander Borisov <borisov@lexbor.com>\n"
            "#\n\n");

    fprintf(fc, "#\n"
            "# This file generated by the program\n"
            "# \"utils/lexbor/encoding/shift_jis_map_decode.c\"\n"
            "#\n\n");

    /* Single index */
    size = sizeof(lxb_encoding_multi_index_jis0208)
           / sizeof(lxb_encoding_multi_index_t);

    for (size_t i = 0; i < size; i++) {
        entry = &lxb_encoding_multi_index_jis0208[i];

        if (entry->codepoint > LXB_ENCODING_DECODE_MAX_CODEPOINT) {
            continue;
        }

        encode_to_file(fc, ref, end, entry->codepoint);
    }

    for (lxb_codepoint_t i = 0xFF61; i <= 0xFF9F; i++) {
        encode_to_file(fc, ref, end, i);
    }

    for (lxb_codepoint_t i = 0x00; i <= 0x80; i++) {
        if (i != 0x5C && i != 0x7E) {
            encode_to_file(fc, ref, end, i);
        }
    }

    fprintf(fc, "\n# END\n");

    fclose(fc);

    return EXIT_SUCCESS;
}
