/*
 * Copyright (C) 2026 Alexander Borisov
 *
 * Author: Alexander Borisov <borisov@lexbor.com>
 */

#include "lexbor/encoding/encoding.h"
#include "lexbor/encoding/multi.h"


int
main(void)
{
    FILE *fc;
    size_t i, size;
    unsigned lead, trail;
    lxb_codepoint_t cp;
    const char *filepath = "./shift_jis_map_encode.txt";

    /* All code points in index jis0208 are in the Basic Multilingual Plane. */
    static bool seen[0x10000];

    fc = fopen(filepath, "w");
    if (fc == NULL) {
        printf("Failed to open file: %s\n", filepath);
        return EXIT_FAILURE;
    }

    fprintf(fc, "#\n"
            "# Copyright (C) 2026 Alexander Borisov\n"
            "#\n"
            "# Author: Alexander Borisov <borisov@lexbor.com>\n"
            "#\n\n"
            "#\n"
            "# This file generated by the program\n"
            "# \"utils/lexbor/encoding/shift_jis_map_encode.c\"\n"
            "# Canonical byte sequences, one entry per encodable code point.\n"
            "#\n\n");

    size = sizeof(lxb_encoding_multi_jis0208_map) / sizeof(lxb_codepoint_t);

    for (i = 0; i < size; i++) {
        /* The index Shift_JIS pointer excludes this range. */
        if (i >= 8272 && i <= 8835) {
            continue;
        }

        cp = lxb_encoding_multi_jis0208_map[i];
        if (cp == LXB_ENCODING_ERROR_CODEPOINT || seen[cp]) {
            continue;
        }

        /* Use the first remaining pointer for each code point. */
        seen[cp] = true;
        lead = i / 188;
        trail = i % 188;

        fprintf(fc, "\\x%02X\\x%02X 0x%04X\n",
                lead + ((lead < 0x1F) ? 0x81 : 0xC1),
                trail + ((trail < 0x3F) ? 0x40 : 0x41), (unsigned) cp);
    }

    for (cp = 0xFF61; cp <= 0xFF9F; cp++) {
        fprintf(fc, "\\x%02X 0x%04X\n", (unsigned) (cp - 0xFF61 + 0xA1),
                (unsigned) cp);
    }

    for (cp = 0x00; cp <= 0x80; cp++) {
        fprintf(fc, "\\x%02X 0x%04X\n", (unsigned) cp, (unsigned) cp);
    }

    /* Encoder aliases do not round-trip through the decoder. */
    fprintf(fc, "\\x5C 0x00A5\n"
            "\\x7E 0x203E\n"
            "\\x81\\x7C 0x2212\n"
            "\n# END\n");

    return (fclose(fc) == 0) ? EXIT_SUCCESS : EXIT_FAILURE;
}
